### ISSUE TITLE
Support for Combat Enhancements

### ISSUE THREAD

**Issue by apoapostolov** [Dorako/pf2e-dorako-ui#1]
Mod repo - https://foundryvtt.com/packages/combat-enhancements

Circular HP gauge around the character token in Combat Tracker is outside the boundaries of the token itself. 

![image](https://user-images.githubusercontent.com/4083812/152389790-3d0cd883-b79e-4e5a-9a37-d572d3c915e4.png)

**Comment by Dorako** [comment]
Should be fixed in next release
