### ISSUE TITLE
Incompatibility with Sidebar, Chat, and Windows Resizer

### ISSUE THREAD

**Issue by MrVauxs** [Dorako/pf2e-dorako-ui#10]
When both of the modules are enabled, there's extra empty space above the chatbox.
![image](https://user-images.githubusercontent.com/32039708/152657969-30476489-e473-4ffa-abec-ff2405987fa2.png)
vs.
![image](https://user-images.githubusercontent.com/32039708/152657987-3bb74f08-8bf1-44c2-8f06-9167637a76dc.png)

**Comment by Dorako** [comment]
I can't reproduce this, so maybe it has fixed itself. Please comment here if you can reproduce in the next release
