### ISSUE TITLE
[Feature Request] Hide Card Stacks sidebar item

### ISSUE THREAD

**Issue by weepingminotaur** [Dorako/pf2e-dorako-ui#100]
I'm sure I'm not the only Foundry user who has zero use for cards. Having an option to hide that Sidebar button would be nice. :)

**Comment by Dorako** [comment]
For features like this, I won't make toggles, but it can be hidden very easily via Custom CSS module by adding the following:
`#sidebar [data-tab=cards] {
    display: none;
}`
