### ISSUE TITLE
Proposal for Super Compact skill check messages

### ISSUE THREAD

**Issue by apoapostolov** [Dorako/pf2e-dorako-ui#111]
In order to further cut down the clutter in the chat, I am proposing a more compact look for skill checks that will save about half the space, and is super useful for group checks and saves, and for the rolling initiative during encounters.

![image](https://user-images.githubusercontent.com/4083812/203526078-994936c0-3498-4379-aa93-324ea76a969d.png)

Success, Critical Success, Failure and Critical Failure could be colors used for the value. If the roll is critical then the box is intense color and the value is white:
* Critical success - intense green roll value background, roll value is white
* Success - normal roll value background, roll value is green
* Failure - normal roll value background, roll value is red
* Critical Failure - intense red roll value background, roll value is white

If the skill check can be used for initiative, the crossing swords icon appear in the lower right corner of the compact box, under the larger value box.

**Comment by MrVauxs** [comment]
I think this would be best paired with PF2e Workbench's collapsible chat cards.

**Comment by MrVauxs** [comment]
Frankly I think it's best to first suggest this TO PF2e Workbench, and then have PF2e Dorako UI stylize it.
Either that or PF2e Dorako UI eats the collapsible chat cards feature.
