### ISSUE TITLE
[Request] Add CRB styling option for Monk's Enhanced Journal

### ISSUE THREAD

**Issue by weepingminotaur** [Dorako/pf2e-dorako-ui#113]
The CRB styling option for journals is awesome. Being able to apply that styling to Monk's Enhanced Journal entries would be equally awesome.

**Comment by Dorako** [comment]
Seems to work?
<img width="1360" alt="CleanShot 2022-11-25 at 22 16 06@2x" src="https://user-images.githubusercontent.com/1561190/204056014-e89e02c3-300a-4e17-85f5-df0f24237ae6.png">
I'm not familiar with the module though

**Comment by weepingminotaur** [comment]
Whoa, it works now across all sheets. Lol, that wasn't the case until recently, I swear. Sorry to waste your time, please close this request. :)

**Comment by Dorako** [comment]
No problem
