### ISSUE TITLE
Module messes up 4.5.0 new Check success display

### ISSUE THREAD

**Issue by Far2Casual** [Dorako/pf2e-dorako-ui#121]
Without Dorako UI:
![image](https://user-images.githubusercontent.com/63196064/207969660-61a2eef3-58f9-4523-81f5-59b2710cec99.png)

With Dorako UI:
![image](https://user-images.githubusercontent.com/63196064/207969727-947c9622-6a98-465b-85ff-a282b7a305f6.png)
Styles on adjusted / unadjusted are ignored and broken.

**Comment by Dorako** [comment]
Turns out it's because the selector requires for the adjusted/unadjusted spans to be in the 'header' and Dorako UI considers only the speaker and metadata section up top to be the header. Will fix by implementing my own rules for those adjustments.

**Comment by Dorako** [comment]
<img width="290" alt="CleanShot 2022-12-16 at 21 27 07@2x" src="https://user-images.githubusercontent.com/1561190/208183535-d8cba187-3a1a-4e62-97ec-b894fa6c5a13.png">
Fixed for next release
