### ISSUE TITLE
New Area part for spells messes up display

### ISSUE THREAD

**Issue by Far2Casual** [Dorako/pf2e-dorako-ui#122]
Shark did a refactor of the area/areasize parts of spells. When activating the UI, the type of area gets messed up now.

Without UI:
![image](https://user-images.githubusercontent.com/63196064/209118863-fe36f628-e610-4680-bef3-e73232b412a9.png)

With UI:
![image](https://user-images.githubusercontent.com/63196064/209119054-a28365e1-4d68-49df-b990-88b79bf3c5e7.png)

**Comment by Dorako** [comment]
Seems to be a simple area.areaType → area.type sorta thing, fixed for next release
