### ISSUE TITLE
Adjust Degree of Success Strikethrough missing

### ISSUE THREAD

**Issue by MrVauxs** [Dorako/pf2e-dorako-ui#124]
![image](https://user-images.githubusercontent.com/32039708/209854842-c9452bf4-be45-4422-8dfd-5aa71396e4d2.png)
![image](https://user-images.githubusercontent.com/32039708/209854846-eb1ae78b-55a4-40ba-82d1-42faa522d0b4.png)

**Comment by Dorako** [comment]
Duplicates https://github.com/Dorako/pf2e-dorako-ui/issues/121
