### ISSUE TITLE
Modified target AC not getting stroke-through

### ISSUE THREAD

**Issue by Marcloure** [Dorako/pf2e-dorako-ui#126]
With PF2e Dorako UI on:
![image](https://user-images.githubusercontent.com/29084710/210103658-ae0f66c1-c6f4-4bda-bdf8-50ae69c8f287.png)

With it off:
![image](https://user-images.githubusercontent.com/29084710/210103685-cb1a08ec-8092-4fad-9146-c774f852c145.png)

There is no other module active in this test case.

**Comment by Dorako** [comment]
Can you reproduce this error with the 1.9.0 pre-release? https://raw.githubusercontent.com/Dorako/pf2e-dorako-ui/main/module.json

**Comment by Marcloure** [comment]
It's working correctly on 1.9.0, good
