### ISSUE TITLE
Compatibility Issue: MLD Combat Round Messages text obscured

### ISSUE THREAD

**Issue by DariusWolfe** [Dorako/pf2e-dorako-ui#128]
Foundry Version: v10
Build: 291
PF2E Version: 4.6.4
Dorako UI Version: 1.9.7
Monk's Little Details Version: 10.5

When using Monk's Little Details and Dorako UI, Dorako UI obscures the text messages from the Combat Round Messages; the messages still show up, but the text is missing/blank. 

![image](https://user-images.githubusercontent.com/63481633/211207027-bda7343a-2ab7-4f87-ad1c-893cb48aa5ae.png)

In the attached image, Dorako UI is enabled on the top, and disabled on the bottom. Tab color is less important, but disabling header colors will revert it to the normal color, but still not show the text.

**Comment by Dorako** [comment]
Fixed in 1.9.8
