### ISSUE TITLE
Avatar reaction to Critical Fumble/Success as World Settings

### ISSUE THREAD

**Issue by Darkluc9850** [Dorako/pf2e-dorako-ui#132]
Hey, I would like to request an option to disable the avatar reactions to every player, so they don't know the outcome, mainly for Hero Point uses.

**Comment by Dorako** [comment]
That already exists?

**Comment by Darkluc9850** [comment]
At the moment, it is a user setting, meaning the players can leave it on.

**Comment by Dorako** [comment]
Making it a world setting is not going to happen, as people have different preferences for style, so it must be possible to disable it on a client bases.
I do however appreciate that it can leak information in a way that GMs might not want at their table.

I think the best option is to use one of those modules that can sync/push client settings to players and then lock the setting.
Ironically the split to submenus has made those not work perfectly right now, but I'm working on that.

**Comment by Dorako** [comment]
<img width="544" alt="CleanShot 2023-02-18 at 21 17 38@2x" src="https://user-images.githubusercontent.com/1561190/219892816-d104f9c0-b5eb-4a26-a568-7b75c40735cb.png">
Module Management+ and Force Client Settings will allow you to pick a client-setting and force it upon your players.
