### ISSUE TITLE
Hide avatar on Hidden rolls not working.

### ISSUE THREAD

**Issue by Gorvaine** [Dorako/pf2e-dorako-ui#134]
![imagen](https://user-images.githubusercontent.com/1600127/213886473-6b26ae50-e4fe-4737-9583-5a2a6780e1ee.png)

**Comment by Dorako** [comment]
Is the token hidden?

**Comment by Dorako** [comment]
Turns out this setting plain up was not implemented since the refactor.
It'll work in the next release:
<img width="306" alt="CleanShot 2023-01-22 at 00 19 16@2x" src="https://user-images.githubusercontent.com/1561190/213893592-e7afcd5c-3a89-42bc-afb8-d288fd92cc31.png">

**Comment by Gorvaine** [comment]
Great! thanks!

Good job with the module. ;)

**Comment by ScyllPoesis** [comment]
Came to report the same behavior, great to see it already being worked on. Echo above, love the style of this UI, keep up the great work. o7

**Comment by Dorako** [comment]
Should be fixed in 1.11.0
