### ISSUE TITLE
[Feature Request] Player Color character sheet sidbar/header

### ISSUE THREAD

**Issue by roguedevjake** [Dorako/pf2e-dorako-ui#135]
A reddit comment had me thinking this could be a cool addition to dorako.

The ability to recolour the red header and side bar of the character sheet with the currently set player colour.

**Comment by Dorako** [comment]
It's an interesting idea, but there are various complications.
I did whip up a blue-themed version though:
![image](https://user-images.githubusercontent.com/1561190/215192272-b5008dfb-95be-4047-8f5a-ac00e88929b4.png)

**Comment by Dorako** [comment]
I included this blue theme and a green one in a recent release
