### ISSUE TITLE
Bug - Player character sheet dark theme wont apply after new update

### ISSUE THREAD

**Issue by roi007leaf** [Dorako/pf2e-dorako-ui#136]
Title, also pressing save settings cycles dark and light for some reason

**Comment by Dorako** [comment]
Yeah there's definitely some jank with settings I will have to look into.
The dark player sheet in the current version is only accessible in the 'maximum' dark theme setting.
I'm still considering how to handle the dark theme settings, but in the next version the PC sheet toggle will either work, or will be gone, with the PC sheets being colored at a "lower" level of dark theme setting.

**Comment by Dorako** [comment]
Dark sheets are now available in the 'application theme' setting.
Hitting save still does the weird 'cycling' though.
