### ISSUE TITLE
Screenshots in Readme

### ISSUE THREAD

**Issue by shemetz** [Dorako/pf2e-dorako-ui#137]
Please add some screenshots to the Readme file of this module!  It would greatly help potential users who are considering this module.

**Comment by Dorako** [comment]
I've been meaning to take new screenshots. I think I will do it for some sort of 2.0 release once the submenu settings are no longer janky.

**Comment by Dorako** [comment]
I'm inching up on a 2.0 release, any screenshots in particular you were thinking about?

**Comment by shemetz** [comment]
I haven't actually been using this module, just saw a few screenshots in the discord.  I think it would be good to show a character sheet (one or two tabs), the chat log with several different types of things being posted, and maybe also a journal entry or a spell window?

**Comment by Dorako** [comment]
Fixed in 2.0.0
