### ISSUE TITLE
(Feature Request) Add support for Force client settings

### ISSUE THREAD

**Issue by uniwars** [Dorako/pf2e-dorako-ui#139]
Hello, it would be really useful to get back the option to use "Force client settings" module with the UI. Or maybe a checkbox for GM to set its settings as world settings if it's easier to do.

**Comment by Dorako** [comment]
There's not a lot I can do on my end, it seems to be just how submenus work, and converting back to non-submenus has problems as well.
However, Force Client Settings has a tool for exactly this reason:
![CleanShot 2023-01-29 at 00 15 42@2x](https://user-images.githubusercontent.com/1561190/215295491-ace65ad7-c9d0-4cc0-a8fa-4854eaf66f9c.png)
Using this, you can still enable the lock for settings that are hidden in submenus, you just don't get the hint text.
