### ISSUE TITLE
Dark Theme Compatibility with PF2E Workbench's Feat/Spell Rarity Colours

### ISSUE THREAD

**Issue by MindWeb125** [Dorako/pf2e-dorako-ui#143]
Hey, just a quick suggestion, I noticed when using the dark theme that the Common rarity Spells/Feats become almost illegible when using Workbench's Rarity Colours option.

![image](https://user-images.githubusercontent.com/105242276/216422232-ea006895-88af-4952-b54b-12af4d0b3ede.png)

Is there a possibility of making this compatible by brightening up the font colour with the dark theme?

Apologies if this is more complicated than I assume.

**Comment by Dorako** [comment]
Ah fun, I actually added support for that minutes after the workbench update was released, but I see that a recent change has caused the load order to swap so the workbench style is overruling my style.
It'll be fixed in next release.

**Comment by MindWeb125** [comment]
Aaah, xdy mentioned they thought you'd already accounted for this. Glad to hear!
