### ISSUE TITLE
Request: Make spell area type localizable

### ISSUE THREAD

**Issue by Cuingamehtar** [Dorako/pf2e-dorako-ui#146]
Hello. Currently spell chat cards print the spell area type as it is used internally. I would like to request making it localizable.

My current solution is inserting 2 lines 
```
let areaType = spell?.system?.area?.type;
let areaTypeLabel = areaType ? i18n("PF2E.AreaType" + areaType.charAt(0).toUpperCase() + areaType.slice(1)).toLowerCase() : "";
```
after
https://github.com/Dorako/pf2e-dorako-ui/blob/35bce85181c03fc1046697e59a367916ab3c7061/modules/message-hooks.js#L269

and changing line 271 to
`areaValue.textContent = area + " " + i18n("PF2E.Foot").toLowerCase() + " " + areaTypeLabel;`
There might be a better way to do it, though.

**Comment by Dorako** [comment]
Looks good to me. Any particular reason you didn't do a PR, considering you had the code already?

**Comment by Cuingamehtar** [comment]
I'm just not used to collaborative work in github. All I've done in github were solo or closed team projects.

**Comment by Dorako** [comment]
Well, congratulations on your first PR then: https://github.com/Dorako/pf2e-dorako-ui/releases/tag/v1.11.16
