### ISSUE TITLE
Application theme dark mode text edit visibility 

### ISSUE THREAD

**Issue by Opzehn** [Dorako/pf2e-dorako-ui#147]
When using the Dark Dorako UI, the text in descriptions when editing becomes nearly impossible to read due to the similar colors.
https://i.imgur.com/xL2OJfG.png
Would be nice to be able to change the text color to something easier on the eyes.

**Comment by Dorako** [comment]
For technical reasons I can't change the text color, but I can change the background to something light, so the dark text is readable.
Where is this field you're editing? I already changed this for PF2e item descriptions and on the player sheet a few versions ago.

**Comment by Dorako** [comment]
Picture related: 
<img width="715" alt="CleanShot 2023-02-11 at 09 15 13@2x" src="https://user-images.githubusercontent.com/1561190/218247981-556408b3-f7f0-4696-b4cc-400db9ea3156.png">
If you're not on >=1.11.13 yet, try if that fixes the issue

**Comment by Opzehn** [comment]
Updating the version fixed it!
