### ISSUE TITLE
[Feature Request] Dark mode for Journals

### ISSUE THREAD

**Issue by L4D15** [Dorako/pf2e-dorako-ui#148]
Using the dark mode styling is a must in my games since you implemented it and journals has become a distracting, bright and blinding white spot when opening them when everything is dark. It would be incredible to have the same dark styling for journals for a complete dark experience :-)

**Comment by Dorako** [comment]
There are two main reasons that journals are exempt from dark theme at the moment (though they are kind of the same reason):

1. I can't know or control the contents people have in journals. If somebody makes a journal and makes some of the text blue, that might look alright on a light background, but be entirely unreadable on a dark background.
2. I am opting out of styling journals from premium modules at all. This means that even if I did implement a sort of 'at-your-own-risk' dark theme for journals, it would not be affecting premium module journals.

Considering dark theme has almost full coverage now, journals *are* a significant gap. I think eventually I'll wind up with some sort of solution for this. I've already made journal dark theme work (see for example the crit deck journals, pic related), but I'm still considering how to deal with aforementioned issues.
<img width="1013" alt="CleanShot 2023-02-11 at 23 07 29@2x" src="https://user-images.githubusercontent.com/1561190/218283138-a545dc1a-2119-4bd9-ae8d-da21dd878a90.png">

**Comment by L4D15** [comment]
Premium modules' journals should be left untouched as they already have quite some custom styling, but an option for regular journals would be welcome. It's pretty difficult to account for all possible formatting someone will do in their journals, but if the user is going to use dark mode, they should take that into account when applying colors to there journals.

This may be just my personal taste, maybe I'm just too used to dark mode from code editors and the like. In any case, thanks for such an awesome theme, your work ins invaluable.

**Comment by Dorako** [comment]
If you're feeling adventurous you can write a small module to inject the class 'dark-theme' into every journal application on render. You'll get something like this:
<img width="1008" alt="CleanShot 2023-02-11 at 23 36 36@2x" src="https://user-images.githubusercontent.com/1561190/218283979-a025b5e0-0274-486a-9677-7f9e663493b6.png">

**Comment by Dorako** [comment]
I included a theme setting for this in 1.11.17
