### ISSUE TITLE
[Feature Request] Savage Worlds Adventure Edition Compatibility

### ISSUE THREAD

**Issue by Deadlander** [Dorako/pf2e-dorako-ui#151]
Please make this mod compatible with Savage Worlds to allow the Pathfinder for Savage Worlds players to use it.

**Comment by Dorako** [comment]
Would I need to do anything beyond marking it as compatible?

**Comment by Deadlander** [comment]
I honestly wouldn't know until it is marked as compatible. I could try it then and let you know later today.

**Comment by Dorako** [comment]
A gave it a quick check. The hotbar was broken since I was only supporting the PF2e-specific one, so I added support for the default Hotbar as well.
![CleanShot 2023-02-14 at 23 09 44@2x](https://user-images.githubusercontent.com/1561190/218874701-c0409933-17b8-4d0e-8ba3-914c9de90535.png)
I imagine a bunch of stuff is broken or could look better, but it seems workable.

**Comment by Deadlander** [comment]
Nice! If I knew the first thing about how to do it, I would offer up help. Unfortunately, my talents lay in fixing people, not code.

**Comment by Dorako** [comment]
I'll push a new release with experimental SWADE support in a minute. I can't support an entire system I don't play myself, but if you eventually make like a "top 5 worst things" I could do some triaging.

**Comment by Deadlander** [comment]
Sounds great! And if you ever want to give it a shot, I am more than willing to run a one shot!

**Comment by Dorako** [comment]
Appreciated! https://github.com/Dorako/pf2e-dorako-ui/releases/tag/v1.11.22 is out now.

**Comment by Deadlander** [comment]
Much appreciated!

**Comment by Dorako** [comment]
![CleanShot 2023-02-14 at 23 50 10@2x](https://user-images.githubusercontent.com/1561190/218881041-2d54e8be-295a-4fac-823b-ff1d0b5f6724.png)
I blocked the complex actor sheets from using dark-theme, so the setting can still be used without looking weird.
Also fixed dark-theme journals rendering weird.
And replaced the paizo red color with the swade red color, but kept the paizo blue.

**Comment by Dorako** [comment]
I've managed to get the token and actor avatars working as well, though I'll need a bit more time to check that I'm not screwing up anything on the pf2e side.

**Comment by Deadlander** [comment]
The latest release is looking good on the PFSW end: 
![image](https://user-images.githubusercontent.com/13036735/218898648-85c816f5-9e71-41bd-a748-849144862f5d.png)
Here's hoping it doesn't screw up the PF2E side! :)

**Comment by Dorako** [comment]
Can you take a picture like this of a PFSW journal and character sheet?
![CleanShot 2023-02-15 at 02 08 40@2x](https://user-images.githubusercontent.com/1561190/218899213-d2048eb3-3196-4733-8302-b52e4970d029.png)
Open developer tools via F12 or ctrl+shift+i or similar, and snap a pic.
And in "Console" see if you can find something like this:
![CleanShot 2023-02-15 at 02 11 08@2x](https://user-images.githubusercontent.com/1561190/218899419-a5855797-03a7-4206-a4a2-e4defa8bff46.png)
It looks like the Dorako UI 'baseline' styling is affecting the sheets, which is intended for "your average" window, but not those of premium modules, so I'd like to try to exclude my messing with them.

**Comment by Deadlander** [comment]
![image](https://user-images.githubusercontent.com/13036735/218900737-88977e59-9ab3-4ba8-8588-1624840eb098.png)
![image](https://user-images.githubusercontent.com/13036735/218900861-0f10bc00-2646-4cf1-863e-fc1775f7f984.png)

Nothing labeled as Dorako exactly. If you want, you can DM me on Discord for faster turn around: James|Knightso/tSmithDinnerTable#0343

**Comment by Dorako** [comment]
It's 3AM for me, but maybe I'll reach out tomorrow

**Comment by Dorako** [comment]
I can't figure out how to DM somebody on discord that I don't share a server with. If you join https://discord.gg/pf2e briefly I should be able to find you (or you me). There's a #pf2e-dorako-ui thread under modules.

**Comment by Dorako** [comment]
Is this thing a module (if so, which one?) or a system thing (if so, how do I access it?) 
<img width="317" alt="CleanShot 2023-02-15 at 18 49 22@2x" src="https://user-images.githubusercontent.com/1561190/219111689-61ba2716-7404-4e03-9ef5-857c89f77007.png">

**Comment by Dorako** [comment]
I think I managed to exclude the SWPF journals and sheets in the latest update, can you confirm?
