### ISSUE TITLE
Chat cards from Damage Log styling with Dorako UI enabled

### ISSUE THREAD

**Issue by notrealdan** [Dorako/pf2e-dorako-ui#152]
Chat cards from the module "Damage Log" are normally color-coded red (for damage taken) and green (for healing), like this:
![image](https://user-images.githubusercontent.com/28198633/218882376-3553edcf-8543-4453-935f-0aeef7ba8f63.png)

With Dorako UI enabled, the cards all look the same, making it less convenient to distinguish at a glance, like this:
![image](https://user-images.githubusercontent.com/28198633/218882507-03ff8266-8aed-42b5-9b95-b1028bfbd1ce.png)

I took those screenshots in a fresh world to make sure there weren't any other modules at play.

Is it possible to have an option to allow those chat cards to keep their original styling?  Or could there be some styling for them that fits the Dorako style, but still maintains some distinction between damage and healing log cards?

**Comment by Dorako** [comment]
Fixed for next release
![CleanShot 2023-02-15 at 02 05 02@2x](https://user-images.githubusercontent.com/1561190/218898637-29b32e93-864f-4088-a0cf-2943e6432a7d.png)
