### ISSUE TITLE
Black Bar on Firefox

### ISSUE THREAD

**Issue by Kyajin0** [Dorako/pf2e-dorako-ui#155]
Hi, not sure if the right place to put this. On Firefox there is a black bar with Dorako UI next to the tabs on the right. This bar doesn't show up on the Foundry desktop client or when I used Chrome. I also tried disabling all other modules and it follows directly from Dorako UI

![image](https://user-images.githubusercontent.com/125595070/219445898-f18dda75-6e79-4b65-a72a-ae3c649d7b61.png)

**Comment by Dorako** [comment]
It's the scrollbar to allow for acrolling the effects panel if you have a loooot of effects. On chromium based browsers I can hide the scrollbar, but firefox doesn't appear to really support this at the moment.
When I get home I can check if it's easy to whip up some custom css to disable the scrolling behaviour if you don't use it.

**Comment by Dorako** [comment]
You can add this to Custom CSS to get rid of the bar (and the scrolling feature):
```css
.effect-panel.dorako-ui {
overflow: hidden;
}```

**Comment by Kyajin0** [comment]
That worked perfectly! Thank you so much
