### ISSUE TITLE
Macros directory washed out

### ISSUE THREAD

**Issue by notrealdan** [Dorako/pf2e-dorako-ui#158]
The macros directory is very hard to read with Dorako UI enabled.  The background and text are both very, very light.
![image](https://user-images.githubusercontent.com/28198633/219904442-046c6065-bce5-4c73-a5c7-e961c44b478b.png)
The macro listed there can hardly be seen.  It wasn't like this as recently as earlier today, so I think this is due to a recent patch.

**Comment by Dorako** [comment]
Fixed in 1.12.4 out now
