### ISSUE TITLE
CSS compatibility issue with Beginner Box journals due to !important use

### ISSUE THREAD

**Issue by yjeroen** [Dorako/pf2e-dorako-ui#160]
![image](https://user-images.githubusercontent.com/1303988/220749322-dfccbbe4-10d1-470d-92ca-467a7a26fc1a.png)

![image](https://user-images.githubusercontent.com/1303988/220749366-9174a2de-e5f2-462c-a08a-4efd7ebdcb31.png)

![image](https://user-images.githubusercontent.com/1303988/220749409-5c667ae8-b4d4-4cf7-82ba-89f15b688fde.png)

**Comment by yjeroen** [comment]
Without the dorako UI CSS, it would look like:

![image](https://user-images.githubusercontent.com/1303988/220749548-12bbd260-f100-4b1d-94da-58088730289f.png)

**Comment by Dorako** [comment]
With my new tech I might be able to apply the dalvyn styling only for non-premium-module journals. Otherwise, disabling the CRB styled journals under misc settings should fix this in the interim.

**Comment by yjeroen** [comment]
I worked around it at the moment via a custom world.css override of the h1234 color and :hover background.

I don't want to disable your CRB journal styling as I love the styling for my own journals in the same world.

**Comment by Dorako** [comment]
Oh I know what's wrong - I was pretty sure I had already made dalvyn styling not be injected into premium modules, but now I realize that Beginner's Box is not on my list.
From your pictures above it the class appears to be pf2e-bb, can you confirm?

**Comment by yjeroen** [comment]
Correct!

**Comment by Dorako** [comment]
I just released v1.12.6 which *should* resolve this issue

**Comment by Dorako** [comment]
I'll assume this is fixed, feel free to re-open if it isn't.
