### ISSUE TITLE
When cast, the "Cost" field of Rituals specifically actually returns the "Cast Time" field

### ISSUE THREAD

**Issue by SkyChronicler** [Dorako/pf2e-dorako-ui#166]
I created a custom ritual. The cast time of the ritual is "Depends", but its "Cost" is "rare incense and offerings worth a total value of 20gp x the spell level". If I drag that item to a PC's sheet, then cast it, the Dorako UI outputs the "Depends" in the "Cost" field at the top of the output. See attached screenshot.
![Capture](https://user-images.githubusercontent.com/127051534/222982046-cea595d4-9c4e-4f2f-8605-12aa9df93e1a.JPG)
![Capture](https://user-images.githubusercontent.com/127051534/222982074-0df1f00d-452c-4344-8ed0-8a8b8f7a53ff.JPG)

I tried it on a ritual that already exists, Consecrate, and noticed the same behaviour. See below.
![Capture](https://user-images.githubusercontent.com/127051534/222982147-7142480d-fdc0-469e-89cf-dba31ebaf4f3.JPG)

**Comment by Dorako** [comment]
Fixed for next release, also added some labels that are missing in the system card
<img width="295" alt="CleanShot 2023-03-05 at 23 18 51@2x" src="https://user-images.githubusercontent.com/1561190/222989066-cea2b7f3-53bf-44ce-86ca-67d7b2f19044.png">
