### ISSUE TITLE
Allow hiding of any right sidebar tab

### ISSUE THREAD

**Issue by PlasticMohawk** [Dorako/pf2e-dorako-ui#167]
The option to hide the Cards tab is great - it would be awesome if I could do this for any tab (and enforce that setting on the player's end).

**Comment by Dorako** [comment]
Hi, you can do this using the new custom css feature in 2.0.0:
![CleanShot 2023-03-06 at 19 32 04@2x](https://user-images.githubusercontent.com/1561190/223199715-b9cc07d7-727a-46c1-b6fe-1f019ee1fe2a.png)
In this picture you can see the data names of the various tabs, for example cards is `.item[data-tab=cards]`.
If you want to hide, for example, playlists, add the following:
`.item[data-tab=playlists] {display: none}`
to the custom CSS section in settings.

As for enforcing the setting for your players, I recommend you use a module like Force Client Settings or Module Management+.
