### ISSUE TITLE
Incompatibility with Illandril's Chat Enhancements

### ISSUE THREAD

**Issue by MrVauxs** [Dorako/pf2e-dorako-ui#17]
Nicknames by default using Dorako UI have a tab before them, which with [Illandril's Chat Enhancements](https://github.com/illandril/FoundryVTT-chat-enhancements) break that modules functionality.

![image](https://user-images.githubusercontent.com/32039708/152980079-d6cc593a-0316-4387-b334-70821a3d8242.png)
(Should read `Sorin [Neutral Bones]`)
vs.

![image](https://user-images.githubusercontent.com/32039708/152980352-f76c8dad-33ac-4534-b80f-1fd14167262f.png)

**Comment by MrVauxs** [comment]
In conjunction with this, it would be nice to be able to just, not have that tab? I'd rather have the names be on the left side of the chat rather than offset to the right.

**Comment by Dorako** [comment]
Will have a look at the name in bracket, the tab is just a holdover from the way I hacked in chat portrait stuff before. The tab should be gone in next release

**Comment by Dorako** [comment]
<img width="319" alt="image" src="https://user-images.githubusercontent.com/1561190/153020367-437f9f20-0ea1-4d58-9d98-626af7ee9307.png">
This is how it looks currently
