### ISSUE TITLE
Canvas unclickable near left-side toolbar

### ISSUE THREAD

**Issue by TomChristoffer** [Dorako/pf2e-dorako-ui#170]
The div containing the lefthand side toolbar icons is bigger than the actual icons, and you can't click, drag och select anything on the canvas behind that container. This is only when using the Compact Ui option.

**Comment by Dorako** [comment]
This was an interesting one. Clicks were getting 'eaten' by an invisible div that needed to be that sorta size to account for modules that add clickable elements to the controls, and it needs to have mouse events to be able to track whether you mouse is nearby.
I reworked the feature in 2.0.2 so it uses an event listener to conditionally show/hide the elements - so now they also only show once the mouse is closer, but go away once the mouse is further away, to ensure you can still click extra elements.
