### ISSUE TITLE
Add styling support for GM Screen module

### ISSUE THREAD

**Issue by PlasticMohawk** [Dorako/pf2e-dorako-ui#172]
Now that GM Screen is being updated again, it would be great to have the styling match the rest of my Dorako UI.

Currently it looks like this: 
![image](https://user-images.githubusercontent.com/5216225/224381010-9f897583-3d95-4cfc-864b-084cced473e4.png)

**Comment by Dorako** [comment]
Interesting. The module appears to have been released in an 'alpha' state just yesterday, so I'll probably wait a bit to ensure the code base is stable.

**Comment by Dorako** [comment]
Closed as the system includes a GM journal, and the above module has been in a pre-release state since march.
