### ISSUE TITLE
'Send' button nonfunctional for deities

### ISSUE THREAD

**Issue by ethasis** [Dorako/pf2e-dorako-ui#176]
![image](https://user-images.githubusercontent.com/96197228/226441523-8d6fc19d-8096-4fc9-bc23-a81f3a917720.png)

This error occurs when attempting to send a deity entry to chat. This template is seemingly no longer provided by the current edition of the PF 2e system.

**Comment by Dorako** [comment]
The 'Send' button functionality won't be maintained - it'll work until it won't.
