### ISSUE TITLE
Dorako UI blocks moving "Custom Hotbar" additional hotbar position.

### ISSUE THREAD

**Issue by tehguitarist** [Dorako/pf2e-dorako-ui#177]
Gotta love module compatibility eh? So the module Custom Hotbar (https://github.com/Norc/foundry-custom-hotbar) has the ability to move the additional hotbar is provides (so you could have them side by side for example. 

Unfotunately with Dorako UI enabled, this is blocked. It looks like the Custom Hotbar module references its position off of the core one, so not sure if there is an interaction there.

Easy way to test, is if you open up developer tools and adjust the --custom-hotbar-chb-x-pos variable without the UI enabled, the hotbar moves side to side. If the UI IS enabled, it doesn't anymore. Not sure if this is because the way the custom hotbar references the core hotbar isn't the best method, or if Dorako UI wraps the element up in a way that another variable is needed to shift its position.

Hope I've provided enough detail. Happy to do some more digging as well of course.

**Comment by Dorako** [comment]
I haven't tested recently, but I believe this was done as a compromise solution to work with both Custom Hotbar, Monk's Hotbar, and the "centered hotbar" option in Dorako UI.

If you want to use the Custom hotbar settings to move the hotbar, you can set the positioning back to absolute like this: 

`.dorako-ui#custom-hotbar {
    position: absolute;
}`

You can also set the offsets there, if you want:
`.dorako-ui#custom-hotbar {
    position: absolute;
    bottom: <yourvaluehere>;
    left: <yourvaluehere>;
}`
