### ISSUE TITLE
Monk's Combat Details format breakage

### ISSUE THREAD

**Issue by DariusWolfe** [Dorako/pf2e-dorako-ui#178]
Foundry Version 10, Build 291
Pathfinder 2nd Edition Vers. 4.9.3
Dorako UI Version 2.0.4
Monk's Combat Details Version 10.1

Since Monk broke Monk's Little Details out into multiple mods, a previously fixed issue has reappeared. Namely, the "Combat Round Messages" is now showing as blank bars colored according to the Chat message header theme setting in Dorako UI, rather than as intended. See image below for context. 

![image](https://user-images.githubusercontent.com/63481633/227757524-7c8a87e2-16ac-47b1-952f-ddfe4e3b54f1.png)

**Comment by Dorako** [comment]
Fixed in 2.0.5
