### ISSUE TITLE
Control bug when using the camera

### ISSUE THREAD

**Issue by medeiros961030** [Dorako/pf2e-dorako-ui#179]
When I have the foundry's active camera mode on the right side, I can't change the options on the left side

In the photo below I have the mouse on top, and the options to change lighting, sound, etc etc do not appear
![image](https://user-images.githubusercontent.com/112792783/228371163-379d7744-3226-41cb-bbce-78f7da70c76f.png)

In the photo below I had to minimize the cameras, then I can change the options between light, token, sounds, tiles, etc.
![image](https://user-images.githubusercontent.com/112792783/228371361-b9830cbb-47c3-4052-afa1-61eedd26a48f.png)

**Comment by medeiros961030** [comment]
just an observation, when I stay in the expanded camera tab mode, and I place the mouse more on the left side, the foundry understands as if my mouse was on top of the icons, thus expanding them
![image](https://user-images.githubusercontent.com/112792783/228372148-89ab708c-2a62-4a02-abfc-54eafc8ae86e.png)

**Comment by Dorako** [comment]
Should be fixed in 2.0.7
