### ISSUE TITLE
Incompatibility with DF Chat Enhancements

### ISSUE THREAD

**Issue by MrVauxs** [Dorako/pf2e-dorako-ui#18]
Most likely CSS fuckery abound. [DFCE](https://github.com/flamewave000/dragonflagon-fvtt/tree/master/df-chat-enhance)'s background on Dorako UI's white text.
![image](https://user-images.githubusercontent.com/32039708/152980659-a567e01f-ffb2-4f51-9495-746bc6811f89.png)

**Comment by Dorako** [comment]
The next release of the theme has an optional for applying player-tint to the header, I think using that setting is best.
