### ISSUE TITLE
Do something smart about the scrollbar for effects and firefox

### ISSUE THREAD

**Issue by Dorako** [Dorako/pf2e-dorako-ui#181]

**Comment by ConflagratedCanine** [comment]
I'd like to add to this and verify that the module has a very persistent scrollbar that remains on the screen even when the chatlog/compendium area is minimized. 

I tried this in both firefox and chrome with only Dorako UI installed and it works fine in chrome, but Firefox sadly refuses to dismiss the scrollbar.

**Comment by Dorako** [comment]
Yeah, the scrollbar is because I made the effect list scroll. Firefox doesn't support invisible scrollbars, which results in the current situation.
A better way to handle it might be to just not enable this feature if the user agent is firefox.

**Comment by Dorako** [comment]
This feature no longer exists.
