### ISSUE TITLE
Experimental Token Icons Setting

### ISSUE THREAD

**Issue by ChaseDonnally** [Dorako/pf2e-dorako-ui#182]
Trying out the new setting for effect on tokens, looks like it's arranging the icons not quite directly around the token.
![image](https://user-images.githubusercontent.com/47797620/231023690-ed0d864c-bcc9-4992-8b7b-f33305ba4865.png)

**Comment by Dorako** [comment]
In 2.1.0 the code only worked right for gridsize = 200px.
In 2.1.1 it should work right for any gridsize - let me know if it doesn't.
