### ISSUE TITLE
Difficult to quickly tell the different between a free action and a single action

### ISSUE THREAD

**Issue by Urumii** [Dorako/pf2e-dorako-ui#188]
I recently noticed that the two icons appear very similar. If I'm quickly looking at a sheet, it is hard to tell the difference between the two icons. Is it possible to increase the empty space so the free action better stands out?
![Free vs Single](https://user-images.githubusercontent.com/119474477/232873996-d93fd2a8-ffdd-4e8c-82dd-f612956a03ec.jpg)

**Comment by Dorako** [comment]
Where is this picture from?

**Comment by Urumii** [comment]
It's from the character sheet of an NPC actor. It is present in any
creature with a free action from the bestiary browser. "Treerazer" displays
the same free action icon for example.

--
Kim DeRider
Owner | Head Instructor

Fight or Flight Academy
7355 Washington Ave S
Edina, MN 55439

952-405-6110 |  <http://www.fightorflightacademy.com/>
http://www.fightorflightacademy.com

**Comment by Dorako** [comment]
Reducing the font weight seems to help very slightly, but it's mostly just a question of resolution
<img width="179" alt="CleanShot 2023-04-20 at 21 21 23@2x" src="https://user-images.githubusercontent.com/1561190/233466472-2312710e-3cbc-46ec-a1fc-84f427e8632e.png">
I'll reduce the font weight for action icons on npc sheets for next release, but it's not going to make a massive difference.

**Comment by Urumii** [comment]
This is great, thank you!

--
Kim DeRider
Owner | Head Instructor

Fight or Flight Academy
7355 Washington Ave S
Edina, MN 55439

952-405-6110 |  <http://www.fightorflightacademy.com/>
http://www.fightorflightacademy.com
