### ISSUE TITLE
Issue: CRB Styling and Critical Hit/Fumble Journals

### ISSUE THREAD

**Issue by Armandeus66** [Dorako/pf2e-dorako-ui#189]
Enabling CRB styling affects the fonts in the PF2E Critical Hit/Fumble journals so that words like "Melee," "Ranged" and so on have some characters replaced with the PF2E action icon characters.

**Comment by hitmahip** [comment]
I'm also experiencing this bug

**Comment by JamzTheMan** [comment]
Would it be possible to not addthe Journal theme class dalvyn-journal for things with critical-deck or fumble-deck classes?

**Comment by Dorako** [comment]
fixed in latest release
