### ISSUE TITLE
Minor CSS Issue with Polyglot

### ISSUE THREAD

**Issue by MrVauxs** [Dorako/pf2e-dorako-ui#19]
When Dorako UI is installed with Polyglot, the delete and language icons are very close together while they should have at least some margin. 
![image](https://user-images.githubusercontent.com/32039708/152981784-ef923f32-226f-4ab4-ac28-f488925b29b6.png)
![image](https://user-images.githubusercontent.com/32039708/152981886-554f2705-6608-4b13-b68b-d75ffb1b1c56.png)

**Comment by Dorako** [comment]
This should be fixed in the next release
