### ISSUE TITLE
Circular Token HUD suggestions

### ISSUE THREAD

**Issue by Dorako** [Dorako/pf2e-dorako-ui#191]
**Known issues**

~~First effect is obscured by the default 'targeted token' indicator. 
Suggested solution: Start at '11 o' clock' rather than 12.~~
First icon is offset by 'one' icon slot as of 2.1.11

~~Effect icon looks aliased.
Suggested solution: Swap draworder so the circle is drawn on top of the jagged stencil'd out image.~~
Haxxer has implemented anti-aliasing via blur, and I included it in 2.1.10

When a token is at non-zero elevation, the text is covered by the effect icons.
Suggested solution: Offset the text somehow. 
Update: This is less of an issue now that the top is free of icons until the token is icon-overloaded.

Some people find the icons too small.
Suggested solution: Make preferences controlling the size/angle of icons.

**Comment by ThingsCouldGetDicey** [comment]
number value of effects is missing.

**Comment by Dorako** [comment]
> number value of effects is missing.

<img width="199" alt="CleanShot 2023-04-26 at 17 59 03@2x" src="https://user-images.githubusercontent.com/1561190/234633524-06b2346e-ed2a-48fa-8e0e-db8a7d5843a0.png">
Stock doesn't do number values for effectIcons

**Comment by Dorako** [comment]
> true but if its possible??

At some point it would be better to just hide the effectIcons entirely and use the effects panel somehow - not saying that itself would be silly, it's just radically different than the current feature.
The part of the code that draws the icons doesn't really know a lot about what the icons mean.

**Comment by Dorako** [comment]
> You could blur the mask you use to stencil the images with - a simple `new PIXI.filters.Blur()` would go a long way to make the edge a bit smoother

I'm going on vacation in a bit, but if you can get it to work I'd be happy to merge it.
