### ISSUE TITLE
Constant ReferenceErrors on renderDialog

### ISSUE THREAD

**Issue by Cuingamehtar** [Dorako/pf2e-dorako-ui#192]
Looks like the most recent update is causing the module to throw an error every time a dialog is rendered.
https://github.com/Dorako/pf2e-dorako-ui/blob/873570c5068a5372cb586c5bd3c6544bd17c21e8/modules/base-theme-hooks.js#L88
Here the `position` is always undefined now.

**Comment by Dorako** [comment]
Yeah I removed three lines but should have removed four. It'll be fixed in next release.
