### ISSUE TITLE
[Feature Request] Monk's Active Tiles Color Contrast

### ISSUE THREAD

**Issue by Crowguard** [Dorako/pf2e-dorako-ui#193]
Some actions in the MATT action list are not the easiest to see for some users when using Dark Mode. Could there possibly be a way to alter these colors in the future? (not a complete list of actions with color issues, let me know if you need one or not.)

![image](https://user-images.githubusercontent.com/99844555/236660745-9042d80f-cb84-481c-aadc-ab6428270c01.png)

And, the auto-complete lists in MATT are nearly white on white when using Dark Mode.

![image](https://user-images.githubusercontent.com/99844555/236660773-6a560788-15cc-4f80-9555-99c5102d3004.png)

**Comment by Dorako** [comment]
I don't use MATT myself, and I haven't seen people report poor-contrast text, so a complete list would be very handy

**Comment by Crowguard** [comment]
Here's all the actions have colors are potentially difficult to see (I wasn't sure about the light gray ones, but I left them just in case).

The main issue seems to be the dark blue text & the dark red text on some actions; though I could potentially see some color impaired people having issues with the purple as well. 
![image](https://user-images.githubusercontent.com/99844555/236735331-bbf8d569-d892-40b5-8527-b5c7b8b75601.png)

As for the actions with auto-complete lists with the white on white text from the screenshot in the first message.

Alter
Filter by Attributes
Landing

**Comment by Crowguard** [comment]
[fvtt-tiledata-tile.zip](https://github.com/Dorako/pf2e-dorako-ui/files/11422933/fvtt-tiledata-tile.zip)

Certainly. Here's the tile template. Instructions on importing it can be found here <https://github.com/ironmonk88/monks-module-wiki/wiki/MATT-Tile-Templates>.

**Comment by Dorako** [comment]
I believe this is fixed, or at least radically improved. Feel free to re-open if I'm wrong.
