### ISSUE TITLE
Dark mode doesn't play nice with Item Piles

### ISSUE THREAD

**Issue by weepingminotaur** [Dorako/pf2e-dorako-ui#195]
<img width="312" alt="Screen Shot 2023-05-10 at 12 42 52 AM" src="https://github.com/Dorako/pf2e-dorako-ui/assets/90105219/057d879f-8ff2-4441-9579-8f8dcebe7198">

**Comment by Dorako** [comment]
fix'd
<img width="319" alt="CleanShot 2023-05-30 at 09 39 03@2x" src="https://github.com/Dorako/pf2e-dorako-ui/assets/1561190/684d6c2c-1649-4a40-85dc-3d8f9a185679">
