### ISSUE TITLE
[Feature Request] Party Overview Text on Dark Mode

### ISSUE THREAD

**Issue by rdgueldener** [Dorako/pf2e-dorako-ui#199]
On the [Party Overview](https://github.com/mclemente/party-overview) module, a majority of the text is black on alternatingly grey / black backgrounds.  Can we make all of the text in this table white for better viewing?

![image](https://github.com/Dorako/pf2e-dorako-ui/assets/133718966/ea474a6c-4359-4d91-acfe-abf5bd887828)
![image](https://github.com/Dorako/pf2e-dorako-ui/assets/133718966/5eacea89-a9cd-48c2-95ae-2f9ceaf640c9)

**Comment by Dorako** [comment]
I can't actually recall whether I fixed this, but with the Party Sheet introduced in 5.4.0 I'll refer to that instead
