### ISSUE TITLE
Proficiencies tab is hard to read in dark theme

### ISSUE THREAD

**Issue by ppaterka** [Dorako/pf2e-dorako-ui#200]
Proficiencies tab in PF2E version 5.0.1 is hard to read

![Screenshot_20230619_131708](https://github.com/Dorako/pf2e-dorako-ui/assets/137064077/bf2aa0fa-08f0-4eb2-a286-08422a3e84ae)

**Comment by Dorako** [comment]
Fixed in 2.2.3, out now
