### ISSUE TITLE
[Bug] Filepicker forced to darkmode when using Filepicker+ addon and invisible Favorite Text

### ISSUE THREAD

**Issue by Leolele99** [Dorako/pf2e-dorako-ui#203]
This bug has been present for longer, but I never had a problem with it until V11. 

In V11 the darkmode in DorakoUI doesn't account for the new V11 favourite entries at the top of the filepicker, which makes them unreadable in darkmoode.

Secondly, whenever both DorakoUI and filepicker+ (a premium module by ripper93) is installed in tandem with dorakoUI, the filepicker is forced into dark mode, no matter the settings. Arguably this could also be a bug fromt he filerpicker+ addon, since it adds a setting that lets user toggle between darkmode (default) and non darkmode for the filepicker. However this setting works in vanilla foundry, but doesn't in DorakoUI.

Hope a fix for this can be found soon, thank you a lot!

**Comment by Dorako** [comment]
The old version of filepicker+ I have is dark mode only, which if why Dorako UI treats it as always dark mode.
I've fixed the favourite text issue though, which should alleviate this issue.
