### ISSUE TITLE
[Bug] Conflict with Button Feel

### ISSUE THREAD

**Issue by Crowguard** [Dorako/pf2e-dorako-ui#206]
Having Button Feel active with Dorako UI causes the Chat Tab to render improperly depending on which Foundry version you're using.

https://github.com/LebombJames/button-feel/issues/2

### Foundry 10.303

Chat Tab button overlaps the chat messages.

![image](https://github.com/LebombJames/button-feel/assets/99844555/891840c6-ccd1-4b11-9610-4cde5cd4ca09)

Dorako 2.2.4
Button Feel 1.1.2
PF2 4.12.9

### Foundry 11.304

Chat messages are instead overlapping the tab buttons.

![image](https://github.com/LebombJames/button-feel/assets/99844555/972b06dc-a3c4-45d3-b633-61811edbfded)

Dorako 2.2.4
Button Feel 1.1.2
PF2 5.1.0

**Comment by Dorako** [comment]
fixed in next release
