### ISSUE TITLE
[Bug] Compendiums with tables of content have a semi transparent background

### ISSUE THREAD

**Issue by Vogliadicone** [Dorako/pf2e-dorako-ui#207]
When I open a compendium with a table of content, the page has a semi transparent background, which makes it hard to read:
![PF2e_1](https://github.com/Dorako/pf2e-dorako-ui/assets/119852651/51d5bd07-c658-45f1-bd61-51a6b76665af)
Without PF2e Dorako UI the same page looks normal:
![PF2e_2](https://github.com/Dorako/pf2e-dorako-ui/assets/119852651/900be6fc-149c-4bb1-be02-3006df0352d3)
The individual pages f.e. for edges looks normal with PF2e Dorako UI:
![PF2e_3](https://github.com/Dorako/pf2e-dorako-ui/assets/119852651/5bf2a21e-052c-48ee-accb-9c748a7fb308)

I just discovered the problem today. I'm not sure, if it came with 2.2.4, but I didn't had this problem a few weeks ago.

Please let me know, if I'm just missing an option in PF2e Dorako UI.

- Foundry VTT: 11.304
- PF2e Dorako UI 2.2.4
- Swade System: 3.0.4
- Savage Pathfinder 3.0.0
- Browser: Google Chrome

**Comment by Dorako** [comment]
Should be fixed in 2.2.5, let me know if it isn't

**Comment by Vogliadicone** [comment]
Thanks, works like a charm!

**Comment by Vogliadicone** [comment]
Right now with PF2e Dorako UI v3.1.10 I have the same problem again. Let me know, if you need more information.

- Foundry VTT: 11.315
- PF2e Dorako UI v3.1.10
- Swade System: 3.2.5
- Savage Pathfinder 3.2.0
- Browser: Google Chrome

**Comment by Dorako** [comment]
Hi, Dorako UI 3.0 split the module in two (Dorako UI and UX), and the 3.1 series of releases are essentially getting rid of all legacy styling (of which the SWADE styling qualified).
If I was you, I'd lock the Dorako UI version to the last 3.0 release. There's no real reason to update it anyway, since there's no SWADE related content in the updates, and potential "feature" style features are in Dorako UX.

**Comment by Vogliadicone** [comment]
Thanks, that worked! Hopefully it will also work with FVTT12. Let's see...

**Comment by Dorako** [comment]
Feel free to let me know if it doesn't - I can't promise I will fix it, but I would definitely consider it.
