### ISSUE TITLE
Chatbox improvements

### ISSUE THREAD

**Issue by Drental** [Dorako/pf2e-dorako-ui#21]
![image](https://user-images.githubusercontent.com/74384067/153253423-c451b032-3cc4-484e-81bb-8ad949d45cf9.png)

Grumpy old man noises

<3

**Comment by Dorako** [comment]
I must admit I never use the chat box for anything besides quick inserting stuff, is this better?
<img width="316" alt="image" src="https://user-images.githubusercontent.com/1561190/153285710-2d3f198f-12d5-449d-8e19-c3e450e78aeb.png">

**Comment by Drental** [comment]
still pretty bad for people who do more text based games, like 50% of the grougs I experience.

**Comment by Drental** [comment]
might be a pick up group thing, my AV and the Pathfinder Society groups often have humor or roleplay bits only in chat and some players prefer using the chat to do most stuff because they are shy.

**Comment by Dorako** [comment]
Because of the size or because it is hard to read?
Ideally I'd want the box to grow with entry size rather than scroll.

**Comment by Drental** [comment]
oh, it's fine to read in your suggestion - it's only the size.
Auto grow and I am fine

**Comment by Dorako** [comment]
Apparently it's non-trivial to auto-grow text fields, but I think these changes put together should be significantly better than before
<img width="318" alt="image" src="https://user-images.githubusercontent.com/1561190/153288377-1101c86e-ebf1-4f37-b864-90a9d8b7e89e.png">

**Comment by Drental** [comment]
significantly better for sure.
I like that the letters are no longer monospace.

**Comment by Dorako** [comment]
If you have samples that are particularly bad I'd love to see them. As I said, in my normal play we never use the chat box for 'chat' so I could use the input.
