### ISSUE TITLE
[PF2 Tooltip] option to remove colors from icons, or standartize them with one color

### ISSUE THREAD

**Issue by apoapostolov** [Dorako/pf2e-dorako-ui#214]
PF2 Tooltip Info panels look too crass with various colors in a non-standardized way, which causes OCD triggers. Is there a chance to get a monochrome or standardized one color for the header icons, rather than the full rainbow of various colors. 

![image](https://github.com/Dorako/pf2e-dorako-ui/assets/4083812/bb3a3ea9-48e4-4bf5-b726-4068b016d81d)

**Comment by Dorako** [comment]
Included in 2.3.5 - default is monochrome, with a setting to enable colorized
