### ISSUE TITLE
High contrast PC sheets

### ISSUE THREAD

**Issue by salinedrip** [Dorako/pf2e-dorako-ui#215]
Hello - I know you do a beastly amount of work for this already, and I am so grateful. I have questions on how to make a custom CSS, as my attempts so far have all failed!

We are trying to use the custom CSS to make a sheet and chat/sidebar that is even higher contrast for a player of ours who is visually impaired - having things like the 'ancestry' and 'speed' text in white, and making the dark theme bg even darker or entirely black. The coloured banners are also a problem for us - I know they can't be changed colours because they're images. Are there any ways to disable the sidebars entirely, or to upload our own custom sidebar instead, using CSS?

Advice would be very much welcome. Dark mode is a good start for us, but the writing in many places is still very beige. Forgive me having to ask when this is already such a massive endeavour, unfortunately not one of us knows anything about coding.

**Comment by Dorako** [comment]
Hi, I actually used to have a setting for PC player sheets where the red banner was removed. It's been gone for quite a while though.
Cora recently made this module: https://github.com/silvative/accessibility-enhancements
![image](https://github.com/Dorako/pf2e-dorako-ui/assets/1561190/29123b18-46d3-49e6-800e-8d18224a0ea8)
![image](https://github.com/Dorako/pf2e-dorako-ui/assets/1561190/de0fb10e-8de5-4d5e-b69b-80d3b73cd808)
It has a setting for turning the PC sheets high contrast either light or dark.
There are currently some conflicts between Dorako UI and Accessibility Enhancements as it is brand new, but I'm planning on supporting it.

I don't think the module is listed yet, but you can install it manually via the manifest https://raw.githubusercontent.com/silvative/accessibility-enhancements/main/module.json

**Comment by salinedrip** [comment]
Hi, thank you so much, that sheet looks absolutely perfect! I have absolutely failed at getting it to work (installed the manifest and absolutely nothing's happened for me) but I'll probably go get to troubleshooting and hope for the best!

**Comment by Dorako** [comment]
Did you enable it in settings?
<img width="800" alt="image" src="https://github.com/Dorako/pf2e-dorako-ui/assets/1561190/5be160e2-af75-4e64-b524-0c9985962047">
