### ISSUE TITLE
test color in dark mode

### ISSUE THREAD

**Issue by medeiros961030** [Dorako/pf2e-dorako-ui#217]
Hello. The tests are clickable skills in the newspapers, when I put them in dark mode, they end up becoming ineligible

![image](https://github.com/Dorako/pf2e-dorako-ui/assets/112792783/92b543d8-1724-474b-a6d8-5e076e932c46)
![image](https://github.com/Dorako/pf2e-dorako-ui/assets/112792783/bc987e47-c7a4-4a7a-82ca-4e322554a56b)

teria como melhorar a cor das letras?

**Comment by Dorako** [comment]
Where is that screenshot from? A journal?
