### ISSUE TITLE
[Abomination Vaults Module] Journal Links Contrast Issues

### ISSUE THREAD

**Issue by 117ksk** [Dorako/pf2e-dorako-ui#221]
Looks like latest version of Dorako UI is conflicting with the Abomination Vaults module journal links. The red and dark blue link buttons are contrasting with the font used. I am using Dorako light mode for following examples:

![image](https://github.com/Dorako/pf2e-dorako-ui/assets/113755707/262328de-f9dc-4291-9c7e-40de5ad7352e)
![image](https://github.com/Dorako/pf2e-dorako-ui/assets/113755707/a765a7bb-6d3b-4aca-a68b-fafeee670647)
![image](https://github.com/Dorako/pf2e-dorako-ui/assets/113755707/c4d05486-2269-47bc-b7a8-da3320fa1030)

**Comment by Dorako** [comment]
Ah, annoying, ty for letting me know. The buttons are not supposed to have colors.

**Comment by 117ksk** [comment]
Latest update seems to have fixed font colors in Abomination Vaults labels! Can mark fixed, thanks!
