### ISSUE TITLE
[BUG] Cannot see any sidebar buttons other than the one selected in Compact UI

### ISSUE THREAD

**Issue by xavien12** [Dorako/pf2e-dorako-ui#223]
When I activate Compact UI I can hover over any other UI element to fade it in, but the sidebar button stays at the one I initially selected. When I try to hover over the area nothing fades in.
![Compact Ui](https://github.com/Dorako/pf2e-dorako-ui/assets/58941502/40beac79-edb9-4ba0-8d69-e14373a1e8a2)

**Comment by Dorako** [comment]
Any errors in console? Do you have the video chat stuff enabled?

**Comment by xavien12** [comment]
Video chat stuff disabled, No errors in the console that are different than the errors without compact UI. 

Edit: It fixed itself the issue can be closed. It seems to be fine after I reloaded all the modules with "find the culprit"

**Comment by Dorako** [comment]
Hm, strange! Feel free to re-open if you can reproduce it.
