### ISSUE TITLE
Adopt DF Chat Enhancement-style roll mode icons

### ISSUE THREAD

**Issue by esheyw** [Dorako/pf2e-dorako-ui#224]
Since DF CE seems dead, and the icons were the only thing from that module that I use and couldn't replicate or replace with a Dorako feature, I figure I'd post this ask. If it's not something you'd consider, I understand. Link to exactly the feature  in question: https://github.com/flamewave000/dragonflagon-fvtt/tree/master/df-chat-enhance#roll-selector-buttons-
Ideally they would stay up to date with the current roll mode (which may have been changed from, ie, a keybind).

**Comment by apoapostolov** [comment]
While I agree that this is a must-have feature, wouldn't it make more sense to have a dev adopt CE than to reimplement for PF2 system only. Since the CE improvements of the chat roll options is system-agnostic.

**Comment by Dorako** [comment]
I think archival is also a popular feature of DFCE, and I'm a fan of the chat-merge functionality.
I've experimented with doing my own variant of chat-merge before, but I think apo is correct that the superior solution would be if somebody else decided to maintain the module (whether that is realistic is another thing entirely).

If nobody picks up DFCE, I could probably implement roll mode buttons and chat-merge, but I'm unlikely to do anything similar to archival.

**Comment by Dorako** [comment]
Part of newest release
