### ISSUE TITLE
Attribute Modifires hard to read in dark theme

### ISSUE THREAD

**Issue by ppaterka** [Dorako/pf2e-dorako-ui#225]
Hi!
Attribute Modifires are hard to read in dark theme in PF2E 5.3.0 version, they changed Ability Modifires to Attribute Modifires in this update, I think this causes the problem.

![Screenshot](https://github.com/Dorako/pf2e-dorako-ui/assets/137064077/cd3f3525-2cf2-4ba0-a38c-dc7de6350d1f)

**Comment by Dorako** [comment]
Should be fixed now, let me know if I missed a spot!

**Comment by ppaterka** [comment]
Now it's better, but writings under stats are still grey
![image](https://github.com/Dorako/pf2e-dorako-ui/assets/137064077/b76bcf9c-bca3-4ffe-a5f3-e6680fb4064c)

**Comment by Dorako** [comment]
Ah, missed those entirely lol

**Comment by Dorako** [comment]
Fixed for next release
