### ISSUE TITLE
Bug - condition text formatted strangely when there is a flat-check in the description

### ISSUE THREAD

**Issue by ditzer252** [Dorako/pf2e-dorako-ui#228]
This is only happening when Dorako UI is the only mod enabled.
![image](https://github.com/Dorako/pf2e-dorako-ui/assets/81697575/a799ce5e-b8f7-403c-b87a-a406dd5a6ec7)

**Comment by Dorako** [comment]
![CleanShot 2023-08-20 at 23 40 41@2x](https://github.com/Dorako/pf2e-dorako-ui/assets/1561190/29d4bebd-751c-42b3-ba61-32ad7ed39e50)
Fixed for next release

**Comment by ditzer252** [comment]
Amazing- thank you!
