### ISSUE TITLE
NPC Saves overlap with immunities

### ISSUE THREAD

**Issue by OrangeyPeel** [Dorako/pf2e-dorako-ui#234]
The section for saving throws on NPC sheets overlap with the immunities, making the immunities impossible to edit as trying to hover over the edit button will cause the saving throw tab to open up
![image](https://github.com/Dorako/pf2e-dorako-ui/assets/143990815/c078412a-2171-4a49-95f3-507dcde89a07)

**Comment by Dorako** [comment]
Fixed in 2.6.6
