### ISSUE TITLE
With dark theme, Reload and Range Increment trait text nearly unreadable in Actions tab

### ISSUE THREAD

**Issue by Hornetstaff** [Dorako/pf2e-dorako-ui#236]
Screenshot with comparison to default theme:

![dark](https://github.com/Dorako/pf2e-dorako-ui/assets/41922942/c6f26c24-3c3a-4a01-876d-a262ac0bbe59)
![default](https://github.com/Dorako/pf2e-dorako-ui/assets/41922942/a75b5d5f-0605-4e4a-8377-2addf6f1238a)

The issue doesn't occur in the Inventory tab, nor with any other trait tags I've been able to find

(Foundry v11 Stable 308, PF2e 5.4.3, Dorako UI 2.6.6)

**Comment by Dorako** [comment]
Fixed in 2.6.7
