### ISSUE TITLE
NPC Save Window Misalignment

### ISSUE THREAD

**Issue by Nickh9676** [Dorako/pf2e-dorako-ui#237]
There is some kind of misalignment with the text and the frame for the saves in NPC character sheets 
![image](https://github.com/Dorako/pf2e-dorako-ui/assets/144157985/4f30fc37-8705-4571-853d-aee3d84e725d)
It all looks good when you hover over the save window, but just glancing at the sheet obscures their bonuses.

**Comment by Dorako** [comment]
Try updating

**Comment by Nickh9676** [comment]
Fixed! Thank you so much.
