### ISSUE TITLE
Monk's Enhanced Journal styling not applying

### ISSUE THREAD

**Issue by L4D15** [Dorako/pf2e-dorako-ui#238]
I think something changed in the Monk's Enhanced Journal module that prevents Dorako from applying the correct styling, making the window not look like the one shown in the feature list.

<img width="1040" alt="Captura de pantalla 2023-09-07 a las 0 07 03" src="https://github.com/Dorako/pf2e-dorako-ui/assets/2948600/b4ff0cec-80d2-46dc-a85d-b56bdab964de">

**Comment by Dorako** [comment]
Yeah that is correct, I noticed this a while ago.
In retrospect I don't think I can support MEJ, as it is a moving target with lots of custom styling, and it massively complicates the already complex layering of journal-related functionality.
