### ISSUE TITLE
NPC sheet issue - Saves UI is visible when it should not be

### ISSUE THREAD

**Issue by Baddiemcnoskill** [Dorako/pf2e-dorako-ui#239]
I think the picture explains better than words could.

![image](https://github.com/Dorako/pf2e-dorako-ui/assets/107281965/8eb47586-ad72-47e6-b2fc-00f6d84c49cd)

**Comment by Dorako** [comment]
Try updating?

**Comment by Baddiemcnoskill** [comment]
Ah yes, that was it. Apologies. I always forget what needs to be maintained when one thing or another updates.
