### ISSUE TITLE
With Enable Chat Merge, merged messages won't have the trash can icon in the top right corner for deleting them.

### ISSUE THREAD

**Issue by GorgoPrimus** [Dorako/pf2e-dorako-ui#240]
![Untitled](https://github.com/Dorako/pf2e-dorako-ui/assets/126842722/716b9614-2a70-4832-9fdc-c9a96b839bd3)

As shown here, the merged half of the message doesn't have the delete button and so can't be deleted except by right clicking it and deleting that way, even if the message above gets deleted first.

**Comment by Dorako** [comment]
In newest release all message buttons show on :hover for merged message:
![CleanShot 2023-09-20 at 20 48 36@2x](https://github.com/Dorako/pf2e-dorako-ui/assets/1561190/1d6bde73-842b-4905-a27d-91cfe0012bf7)
