### ISSUE TITLE
Monk's Sound Enhancement Tracks too dark

### ISSUE THREAD

**Issue by Peach774** [Dorako/pf2e-dorako-ui#246]
![image](https://github.com/Dorako/pf2e-dorako-ui/assets/5171184/817e536d-b4c7-4b8e-9b7c-a1aa8175572c)
Monk's sound enhancement adds a way to view tracks in a playlist and dark mode makes the test hard to read.

**Comment by Peach774** [comment]
I don't want to make a huge stink about this, but I was hoping to check in on an update on this? it sorta just needs the font changed to like - white or something.

**Comment by Dorako** [comment]
Hi, no worries, you're always welcome to bump old issues.
While a picture is worth more than a thousand worths, I would love to have reproduction steps for producing the picture though.

**Comment by Dorako** [comment]
<img width="476" alt="image" src="https://github.com/Dorako/pf2e-dorako-ui/assets/1561190/c1842f81-45e1-4e28-83d3-080879a5fbe4">
<img width="400" alt="image" src="https://github.com/Dorako/pf2e-dorako-ui/assets/1561190/1979114d-5135-4da2-927b-d6cbc9781596">
fix'd for next release

**Comment by Peach774** [comment]
> <img alt="image" width="476" src="https://user-images.githubusercontent.com/1561190/283605285-c1842f81-45e1-4e28-83d3-080879a5fbe4.png"> <img alt="image" width="400" src="https://user-images.githubusercontent.com/1561190/283605292-1979114d-5135-4da2-927b-d6cbc9781596.png"> fix'd for next release

THANK YOU
