### ISSUE TITLE
NPC UI makes Saving Throw mods hard to read

### ISSUE THREAD

**Issue by NKatevas** [Dorako/pf2e-dorako-ui#248]
![image](https://github.com/Dorako/pf2e-dorako-ui/assets/83019473/e999e648-8e8e-4c3a-8e42-8ff3cc5736d5)

You need to hover over the mods in order to read them. Is this a bug or did I do something wrong on my side?

**Comment by Dorako** [comment]
Can't reproduce, are you using latest everything? 
![CleanShot 2023-10-06 at 22 36 44@2x](https://github.com/Dorako/pf2e-dorako-ui/assets/1561190/cdd4d9c9-bdc6-474f-9487-a27f4cbfcf8f)

**Comment by NKatevas** [comment]
I updated pf2e and it did the trick it seemed
