### ISSUE TITLE
Skill Editor Hud too light on dark mode

### ISSUE THREAD

**Issue by Peach774** [Dorako/pf2e-dorako-ui#249]
![image](https://github.com/Dorako/pf2e-dorako-ui/assets/5171184/e98ff8f5-09d8-449d-8aab-447e376553f3)
You can't see the skill names

**Comment by Dorako** [comment]
Where is that screen from?

**Comment by Peach774** [comment]
> Where is that screen from?

When you go in to an NPC and edit their skills, thats the window that opens

**Comment by Dorako** [comment]
Should be fixed in one of the recent releases
