### ISSUE TITLE
Foundry 2 Theme issues

### ISSUE THREAD

**Issue by Dorako** [Dorako/pf2e-dorako-ui#251]
Known issues:

**Comment by uniwars** [comment]
Hi, here is some modules I found to have issue with the theme :

Modules not supported for the button styling : 
Token attacher
Levels
Patrol
Z Scatter
DF curvy wall
Monk's wall enhancement
Stairways
Monk's sound enhancement
Dungeon draw
FX master

Modules which need some styling :
Monk's active tile triggers
Monk's tokenbar
Tokenizer

Maybe Token action hud to make toggle color orange instead of blue

Heartbeat's little heart icon on the top right is also weird

**Comment by pedrogrullada** [comment]
Hello, adding a little thing to the list: Workbench's condition manager macro gets a little messed up by Foundry2, checked in both Chrome and Electron client.
![image](https://github.com/Dorako/pf2e-dorako-ui/assets/103401186/53d3c6ba-3624-45e6-bcee-ce2c6e65f14b)

**Comment by Dorako** [comment]
![CleanShot 2023-10-20 at 00 45 36@2x](https://github.com/Dorako/pf2e-dorako-ui/assets/1561190/95625528-6ff1-41f2-8904-9b83efd30009)
Fixed for next release

**Comment by uniwars** [comment]
I edited my message to remove all the updated things

**Comment by joshua-igor** [comment]
Tables has rows with unreadable text. As an example the Druid table listing the Class Features has every even level being unreadable:

![image](https://github.com/Dorako/pf2e-dorako-ui/assets/19159042/3bf3324f-bd55-473c-b984-f10f85290f93)

And also the Spells per Level table:
![image](https://github.com/Dorako/pf2e-dorako-ui/assets/19159042/f53dd22e-b95d-4fc3-87ad-420a23d081dd)

**Comment by joshua-igor** [comment]
The Spell Preparation table has unreadable text and buttons on the headers:

![image](https://github.com/Dorako/pf2e-dorako-ui/assets/19159042/49113fd4-a8d1-4a7e-95d4-59ab81db757f)

**Comment by joshua-igor** [comment]
The Biography page on the Character Sheet has fields that do not fit the content, making it impossible to edit text.
![image](https://github.com/Dorako/pf2e-dorako-ui/assets/19159042/295e681a-d5b7-4aa9-b448-fb20cecf1ee0)

It also has this red button that I'm not sure what it is:
![image](https://github.com/Dorako/pf2e-dorako-ui/assets/19159042/ab7ed917-8ce8-417a-baf4-e895b567f8fc)

**Comment by Dorako** [comment]
Those a scrollbars, but those fields should probably not be "standardized input height", so the scrollbar shouldn't be there.

**Comment by Dorako** [comment]
@joshua-igor 
![CleanShot 2023-10-21 at 12 40 58@2x](https://github.com/Dorako/pf2e-dorako-ui/assets/1561190/20c47510-bb60-4d5d-a61d-de742fd2e812)
Fixed for next release, thanks for the reports.

**Comment by joshua-igor** [comment]
You work incredibly fast.... Here I was doubting if the fixes would be ready before the next session next week.... Thanks a lot!

**Comment by Dorako** [comment]
@uniwars 
![CleanShot 2023-10-21 at 13 49 39@2x](https://github.com/Dorako/pf2e-dorako-ui/assets/1561190/77d5a9d3-4d80-4de7-a0c1-1a0bb50dc939)
<img width="1190" alt="image" src="https://github.com/Dorako/pf2e-dorako-ui/assets/1561190/df321988-636a-4db6-b1b2-3b22410c052e">
<img width="1031" alt="image" src="https://github.com/Dorako/pf2e-dorako-ui/assets/1561190/d27ab492-bc63-4b98-be57-780c9811ff0b">

Fixed MLD HUD, MTT, and Tokenizer. Let me know if I missed a spot, ideally with something I can import.

**Comment by Dorako** [comment]
> You work incredibly fast.... Here I was doubting if the fixes would be ready before the next session next week.... Thanks a lot! BTW, does this also fix the Bio field on the character sheet when viewed with only "Observer" access?

![CleanShot 2023-10-21 at 13 59 25@2x](https://github.com/Dorako/pf2e-dorako-ui/assets/1561190/8eaddcf8-0736-43a1-9efb-a2968f080795)
No, but that appears to be a system issue, not a styling one. I don't see the data when the styling is disabled either.

**Comment by Dorako** [comment]
Or I guess there's no way for them to render like inputs either. I made it look like this:
![CleanShot 2023-10-21 at 14 22 33@2x](https://github.com/Dorako/pf2e-dorako-ui/assets/1561190/d0e09346-a4b3-4ba9-9eab-68c598739043)

**Comment by joshua-igor** [comment]
![image](https://github.com/Dorako/pf2e-dorako-ui/assets/19159042/2cb8b3b4-91f5-4a44-a2e8-a1f11b5d9b11)
The variable casting time icon on the Compendium Browser is invisble.

**Comment by joshua-igor** [comment]
![image](https://github.com/Dorako/pf2e-dorako-ui/assets/19159042/73b7c4e2-9b8e-4aa8-8e80-7522ed99e9f1)
The "Worn" icon on the character's inventory is also invisible. Only the "Worn (Armor)" is visible.

![image](https://github.com/Dorako/pf2e-dorako-ui/assets/19159042/24c93936-c629-4985-9580-610cdde63940)
Also, the "Stowed" icon is invisible when inside a backpack.

**Comment by pedrogrullada** [comment]
Hello, PF2e Perception selection is not highlighted anymore in Foundry2 since at least v2.11.5 in the electron client, while on Chrome and Firefox the window just isn't styled. Seems like something recent broke it?
![image](https://github.com/Dorako/pf2e-dorako-ui/assets/103401186/a2ef3dc5-c56c-4188-aacf-a9546e548657)
![image](https://github.com/Dorako/pf2e-dorako-ui/assets/103401186/8b161410-27f8-4bdc-9ac9-b726b496a175)

**Comment by Dorako** [comment]
I fixed the action cost icons and pf2e-perception intregration. The worn icon is on my list, but it needs a different solution, so I can't just fix it.

**Comment by joshua-igor** [comment]
PF2e Toolbelt's Hero Actions text when there are no Hero Points is unreadable. 
![image](https://github.com/Dorako/pf2e-dorako-ui/assets/19159042/e46f7811-d164-46fd-ab53-033d4b6d7762)

The "Use" button when there is a Hero Point is also unreadable.
![image](https://github.com/Dorako/pf2e-dorako-ui/assets/19159042/0c2681cf-e149-41cc-b5c9-c75583b541e5)

**Comment by Dorako** [comment]
@joshua-igor 
![CleanShot 2023-10-28 at 16 37 12@2x](https://github.com/Dorako/pf2e-dorako-ui/assets/1561190/74adc569-4aca-4d41-ac8c-5d94901d6708)
How do I produce the red "You must discard (2) Hero Action" text?

**Comment by joshua-igor** [comment]
@Dorako You have to spend the Hero Point from the player's sheet without discarding a card.

**Comment by joshua-igor** [comment]
The modifier from a roll while using "Better Dice Formulas" is unreadable.
![image](https://github.com/Dorako/pf2e-dorako-ui/assets/19159042/3c70354f-3b2d-4556-b318-ba37b1a35b8d)

PS: This also happens when using the original Dark theme.
![image](https://github.com/Dorako/pf2e-dorako-ui/assets/19159042/915e5a93-75af-449f-960a-5d1c50b44d5f)

**Comment by Dorako** [comment]
@joshua-igor That module seems pretty broken when used with pf2e, even if I fix the colors.
![CleanShot 2023-10-30 at 01 20 37@2x](https://github.com/Dorako/pf2e-dorako-ui/assets/1561190/111414ab-e9a7-413a-92fa-80923a12afef)
It doesn't appear to understand damage types at all

**Comment by joshua-igor** [comment]
@Dorako I'm reporting issues to that module author as well.

**Comment by Dorako** [comment]
Closed, refered to https://github.com/Dorako/pf2e-dorako-ui/issues/275
