### ISSUE TITLE
Small change to Monks css

### ISSUE THREAD

**Issue by ironmonk88** [Dorako/pf2e-dorako-ui#253]
Line 580, monks.css
```
.monks-enhanced-journal .tab-bar .journal-tab {
  border-radius: 3px;
}
```
Should be
```
.monks-enhanced-journal .tab-bar .journal-tab {
  border-top-left-radius: 3px;
  border-top-right-radius: 3px;
}
```

**Comment by Dorako** [comment]
Thanks, I've included it for next release.
However, I think that the MEJ support in Dorako UI is essentially non-existing at this point.
For a while I had a really thorough styling like this, but eventually it broke.

![](https://raw.githubusercontent.com/Dorako/pf2e-dorako-ui/main/promo/web/monks.jpg)

**Comment by ironmonk88** [comment]
The stylings had a major change awhile back to integrate `Arius Planeswalker's Stylish Journal for Monk's Enhanced Journal` and because it was time.  The styles were very convoluted and out of date.  So I spent some time to clean up the styles and switch to using css variables.  Which should, in theory... make it a lot easier to alter those settings, but also unfortunately made a lot of older styles out of date.

**Comment by Dorako** [comment]
Good to know, I might revisit at a later date.
I have far too many layers of journal modifications in play, and supporting all combinations of them at the same time as ensuring premium module journals (that I don't have acces to) were unaffected, turned out to be very time consuming.
