### ISSUE TITLE
Jump to Bottom in Chat window

### ISSUE THREAD

**Issue by biggusbeardus** [Dorako/pf2e-dorako-ui#257]
Issue: "Jump to Bottom" button appears in Chat window when chat is cleared and will not go away on client side.

Steps to recreate: Clear chat window when chat is full.

UI Version: 2.10.10
System: Pathfinder 2e 5.7.2
Foundry version: 11.313
Hosting: Forge
Browser: Chrome

**Comment by Dorako** [comment]
![image](https://github.com/Dorako/pf2e-dorako-ui/assets/1561190/de70f0f1-2b41-4e04-afa2-9aec0a4202f3)
Sasmira managed to reproduce the issue with no UI module active, so for now I'm treating this as a core issue
