### ISSUE TITLE
NPC Inventory - Item Icon Box Stretched

### ISSUE THREAD

**Issue by relaytheory** [Dorako/pf2e-dorako-ui#259]
The icon boxes have been stretched horizontally on the NPC Sheet, Inventory tab.
Player sheet unaffected.

This can be reproduced by loading in PF2e Dorako UI with default settings.
Create an NPC token, then drag an item from Compendium into NPC inventory.

FoundryVTT v11 Build 308
PF2e 5.7.3
DorakoUI v2.11.3

![Screenshot_7](https://github.com/Dorako/pf2e-dorako-ui/assets/32248765/4f9dba1f-7b30-402b-8d0c-cbe404310074)

**Comment by Dorako** [comment]
As far as I understand it, this is a system issue that only manifests in Firefox.
Can you try with Dorako UI disabled?

**Comment by relaytheory** [comment]
It looks like you are right, this is a system issue, not a DorakoUI one!
