### ISSUE TITLE
Confetti Location Conflicts with Dice Tray

### ISSUE THREAD

**Issue by goodkinghadrian** [Dorako/pf2e-dorako-ui#26]
A recent update moved the Confetti module to the lower-right corner of the panel, but the Dice Tray module uses the same location, so the Confetti interactable overlaps Dice Tray's Roll button.

![confetti](https://user-images.githubusercontent.com/29682568/154997030-20a137df-48d8-477b-9847-26f809d613c9.PNG)

**Comment by Dorako** [comment]
Yeah this was a temp solution until I fired out why it was hidden by some overflow setting somewhere. In the next release it'll be back in its normal place.
