### ISSUE TITLE
Images not found when server has a route prefix.

### ISSUE THREAD

**Issue by JDCalvert** [Dorako/pf2e-dorako-ui#260]
The recent change to some file paths (seen here: https://github.com/Dorako/pf2e-dorako-ui/compare/v2.10.11...v2.11.0#diff-e0de0a521fc8eb551a91d0f714d18237b42c7f026b2707d6c767ada667804cb0R148) has broken these images when the server has route prefix set.

This means that anything that uses these images (especially the backgrounds) is missing, making a lot of text illegible.

**Comment by Dorako** [comment]
Can you verify that this is fixed in 2.11.5?

**Comment by JDCalvert** [comment]
That's sorted it, thank you!
