### ISSUE TITLE
"Remove attack info from damage roll" not currently working.

### ISSUE THREAD

**Issue by RorschachsDream** [Dorako/pf2e-dorako-ui#261]
Foundry 11 Build 313, PF2E version 5.7.4, Doroko version 2.11.6

Disabled all modules except Doroko's to make sure it was just this module and not a conflict.

Have Chat Merge & remove attack info from damage roll enabled.

![image](https://github.com/Dorako/pf2e-dorako-ui/assets/96325004/e9e7ee6c-1031-478d-ae93-eb036be4b6dc)

As you can see, the attack tags (Attack/Evocation/Fire/Magical) are still present on the damage roll.

**Comment by Dorako** [comment]
Fixed in 2.11.7
