### ISSUE TITLE
MATT trigger font hard to read on dark ui

### ISSUE THREAD

**Issue by Peach774** [Dorako/pf2e-dorako-ui#266]
![image](https://github.com/Dorako/pf2e-dorako-ui/assets/5171184/08bcd9b0-2414-4fe1-8740-d0f54ef2a994)
the number here is hard to read

**Comment by Dorako** [comment]
I don't use MATT so you'll have to provide very specific reproduction steps.

**Comment by Peach774** [comment]
> I don't use MATT so you'll have to provide very specific reproduction steps.

Its literally just any action you set for it - the font is purple so its hard to read against the black background.
As an example, if you create a new tile, theres the triggers tab. Under the triggers tab is the actions tab. If you click the + you can create an action. Any of them that have an input field, that input field in the finished action is the dark purple font

**Comment by Dorako** [comment]
![CleanShot 2023-11-11 at 20 38 18@2x](https://github.com/Dorako/pf2e-dorako-ui/assets/1561190/62939586-8c82-413c-bbc6-68a2fcfedaaa)
Will be using the same colors I picked for the foundry 2 theme in the next release

**Comment by Peach774** [comment]
> ![CleanShot 2023-11-11 at 20 38 18@2x](https://user-images.githubusercontent.com/1561190/282262256-62939586-8c82-413c-bbc6-68a2fcfedaaa.png) Will be using the same colors I picked for the foundry 2 theme in the next release

![image](https://github.com/Dorako/pf2e-dorako-ui/assets/5171184/8f2f7a08-4806-424a-9bc8-591923915ae0)
One of the fonts is still hard to read
