### ISSUE TITLE
Chat Header Theme Broken

### ISSUE THREAD

**Issue by Azr-e** [Dorako/pf2e-dorako-ui#268]
The Chat message header theme is broken and doesn't change the chat headers in 3.0.
![image](https://github.com/Dorako/pf2e-dorako-ui/assets/107274954/ac4dc8ed-59b8-4b30-beb6-6c34dee3aa14)
![image](https://github.com/Dorako/pf2e-dorako-ui/assets/107274954/8eb03978-638e-4fb9-9036-eefe049b91c8)

**Comment by Dorako** [comment]
Fix'd for next release
