### ISSUE TITLE
Background blocked out when using module (Yenders Scene Actors)

### ISSUE THREAD

**Issue by demotech89** [Dorako/pf2e-dorako-ui#269]
I have disabled every module and found that Dorako-UI is causing a conflict with Yenders Scene Actors module. Further troubleshooting of the module shows that the setting the Application Theme in the Dorako UI to CRB Inspired (dark) is the only setting that places a giant greyish box over the background as shown in the images I am posting. I just wanted to make you aware because I love the Dorako UI and the dark theme is by far my favorite. Unfortunately I can not use it at this time due to it hiding the background when scene actors are enabled. 
![image 1](https://github.com/Dorako/pf2e-dorako-ui/assets/147771452/61a89eb7-8911-4e4e-8bb9-b44be8cf6051)
![image 2](https://github.com/Dorako/pf2e-dorako-ui/assets/147771452/ae81492d-ac0f-49db-9167-0f26c1ecfc86)

**Comment by Dorako** [comment]
That's a cool module, I might try that for next session.
Fixed for next release:
![CleanShot 2023-11-18 at 08 35 02@2x](https://github.com/Dorako/pf2e-dorako-ui/assets/1561190/fe836137-9112-4d72-82d7-2d96ddb6f35a)

**Comment by demotech89** [comment]
That is awesome and quick turn around. You all rock! Looking forward to the next release!
