### ISSUE TITLE
Core Rulebook theme issues

### ISSUE THREAD

**Issue by Dorako** [Dorako/pf2e-dorako-ui#274]

**Comment by elongpre** [comment]
First off, your work is amazing. Thank you!
Here are some things I'm seeing which might help improve the look. 
Active Modules: PF2e Dorako UI, PF2e Dorako UX, The Forge, Tidy UI - Game Settings.

The biggest reason I love your module is the Player Color Chat Headers, however I'm finding them difficult to use with the latest update.

Settings:
![D_Settings](https://github.com/Dorako/pf2e-dorako-ui/assets/1074802/d2f62447-92fe-463f-8d61-8f2d39ce37a2)

The switch to using backround-blend-mode: screen turns the player color into this pastel color.
In addition to inaccurately portraying the player's chosen color, this breaks the display of the player's name.
The previous functionality to change to a light colored font based on player color isn't adjusting to the basically forced lighter background. Here you can see where I changed the player's color from the default purple, then only changing the luminosity setting to the point where it switching (159). 
![image](https://github.com/Dorako/pf2e-dorako-ui/assets/1074802/1b15865a-cf9a-404e-886e-f665591cfa1d)

I believe if you swapped CRB setting for the background-blend-mode to overlay, these issues would be solved. But I am also a casual at best! So I'm sure an expert like you might know an even better solution.

**Comment by Dorako** [comment]
I'm still working on some quirks related to the headers, but it's intended to look like normal.
![CleanShot 2023-11-25 at 22 00 16@2x](https://github.com/Dorako/pf2e-dorako-ui/assets/1561190/0766e201-61f6-45ad-86b3-5ab5a6e3ff2b)
This is how it looks for me as of 3.1.2

**Comment by elongpre** [comment]
Oh! Wow, I didn't realize I was behind in updates.
My posts are using 3.1.0!
I see Forge has *just* now given me access to 3.1.1
And I look forward to 3.1.2! I know you are are making lots of tweaks with the 3.1.0 refactor and I was hoping to help. But seems like you're already 2 steps ahead of me!

Thanks again for all your hard work!

**Comment by Dorako** [comment]
> Oh! Wow, I didn't realize I was behind in updates. My posts are using 3.1.0! I see Forge has _just_ now given me access to 3.1.1 And I look forward to 3.1.2! I know you are are making lots of tweaks with the 3.1.0 refactor and I was hoping to help. But seems like you're already 2 steps ahead of me!
> 
> Thanks again for all your hard work!

No problem - you're welcome to join us on the pf2e community discord https://discord.gg/huQ9KWSa 
There's a Dorako UI/UX thread, so if you see anything off that's a great place to document it.

**Comment by pedrogrullada** [comment]
Testing out the CRB Window App and App theme with light colour scheme, and found a few quirks. Some menu buttons are unreadable unless highlighted, such as the save buttons on Configure Settings and Module Settings menus.
![image](https://github.com/Dorako/pf2e-dorako-ui/assets/103401186/015f209c-0732-4d84-899b-2a5e2a3d5849)
![image](https://github.com/Dorako/pf2e-dorako-ui/assets/103401186/d7b71159-79bf-45fa-bb6d-130042c6b649)

Same thing happens with damage roll dialogs
![image](https://github.com/Dorako/pf2e-dorako-ui/assets/103401186/ec4a3c64-9f88-4dd6-95d7-d41ea6ada280)
![image](https://github.com/Dorako/pf2e-dorako-ui/assets/103401186/7101d58a-828b-41d8-a572-12e6b76cc424)

I've seen it in other buttons as well, such as when you edit language or currencies on the PC sheet. The common factor seems to be white buttons that include some kind of icon? But anyway, that's all I've got!

**Comment by Dorako** [comment]
Hi, this affects all "bright" buttons in the CRB light theme, and is fixed for next release.
