### ISSUE TITLE
Completely changed the UI look, unable to return to way it was.  Setting are a mess.   

### ISSUE THREAD

**Issue by Albireookami** [Dorako/pf2e-dorako-ui#276]
Glass colored player headers on chat cards gone, the buttons on spells are the wrong color, and I can't figure out how to return them to the proper color I prefer so its readable. 

Skill modifier color is horrible, looks awful on green remaster.  Unable to change anything back to how it was pre most recent update.

**Comment by Dorako** [comment]
Hi, you can either roll back to the earlier version and lock it (which will slowly degrade as the system updates) or you can provide reproduction steps for the issues you are seeing.
I have created threads for each theme, I assume you are talking about this one:
https://github.com/Dorako/pf2e-dorako-ui/issues/274
