### ISSUE TITLE
Initial 3.1.0 load looks weird, but looks as expected after picking a theme

### ISSUE THREAD

**Issue by JesterOC** [Dorako/pf2e-dorako-ui#277]
After updating to the latest today the upper tabs were right against the top window and when I went to the Manage Modules screen none of the module names were visible. Had to search for UI for find the module to remove it.

**Comment by Dorako** [comment]
Not sure what the first part of sentence, but as for the second part, it seems to go away once you select one of the theme settings:
<img width="719" alt="image" src="https://github.com/Dorako/pf2e-dorako-ui/assets/1561190/991b2d87-55d0-4e54-bed1-f525aafae7ce">
<img width="719" alt="image" src="https://github.com/Dorako/pf2e-dorako-ui/assets/1561190/68922c98-4b67-4b99-aabf-ffe5c7f94f6f">
![Uploading image.png…]()

**Comment by JesterOC** [comment]
Thank you I was just going to followup with that info. I found that the window theme was set to none. I selected one and it is back

**Comment by Dorako** [comment]
Can you confirm that selecting "none" once again also looks as expected, eg. vanilla foundry?

**Comment by JesterOC** [comment]
About the first line, I think the upper tabs used to be a few pixels lower. That was my initial impression 

![image](https://github.com/Dorako/pf2e-dorako-ui/assets/954708/23dfd36e-eaeb-40be-9464-0b4b115efe26)

**Comment by Dorako** [comment]
Ah I see, yeah I'll need to add a margin there.
If you look closely, you'll see that the entire sidebar has been changed.

**Comment by JesterOC** [comment]
Yes. Switching back to No theme gives back vanilla foundry. So just the initial transition from previous to now seemed to do it.

**Comment by Dorako** [comment]
The window app theme default key was set "crb-light" which is an illegal value. I've corrected it to "crb", which should resolve this issue.
