### ISSUE TITLE
Additional Character Sheet Color Schemes

### ISSUE THREAD

**Issue by ChaseDonnally** [Dorako/pf2e-dorako-ui#282]
I'd love a few additional character sheet color schemes to pick from.

I feel like a purple (maybe #3B0062, based on the "Expert" purple) and a gold ( similarly, #634304, based on the "Master" color) would both be good additions.

**Comment by Dorako** [comment]
I'll do a purple one and a black one - I'll skip a yellow for now, seeing as the text in the sidebar is quite yellow, and I'm not planning on adjusting it for one specific theme.

**Comment by Dorako** [comment]
Included in 3.1.13
