### ISSUE TITLE
Core Rulebook Theme background broken with 3.1.11

### ISSUE THREAD

**Issue by xKillerbees** [Dorako/pf2e-dorako-ui#283]
![image](https://github.com/Dorako/pf2e-dorako-ui/assets/2941079/9901f93b-146d-4f21-85d2-fe0f5adfaeda)

**Comment by Raileth** [comment]
![dorako-select tile](https://github.com/Dorako/pf2e-dorako-ui/assets/7972292/0c1f1d1e-9476-45e1-9dab-4cd2e0af1132)
I've had a similar issue with this theme - particularly when using the select file dialogue in the tiles menu. The text is white against a light background and unreadable.

**Comment by Dorako** [comment]
> ![image](https://github.com/Dorako/pf2e-dorako-ui/assets/2941079/9901f93b-146d-4f21-85d2-fe0f5adfaeda)
> 
> 

Can you try making any change to settings and saving? If it still doesn't load, try reinstalling - it seems like the background asset is missing.

**Comment by Raileth** [comment]
I've reinstalled and changed settings, however on the Core rulebook window setting with default app clour scheme its still white text on a light background for the file picker

**Comment by Raileth** [comment]
I've found the offending module - filepicker+ - thanks for the help

**Comment by Dorako** [comment]
The background issue with settings extender should be fixed in 3.1.12
