### ISSUE TITLE
Dark mode readability issue

### ISSUE THREAD

**Issue by Araluen124** [Dorako/pf2e-dorako-ui#285]
The sheet is kinda hard to read in dark mode now
![image](https://github.com/Dorako/pf2e-dorako-ui/assets/104476123/9b954e1f-f8f6-46a4-8600-a0173673b4cf)

**Comment by Araluen124** [comment]
Just a little suggestion but maybe a brighter red would be easier to read

**Comment by Dorako** [comment]
<img width="843" alt="image" src="https://github.com/Dorako/pf2e-dorako-ui/assets/1561190/4b207bf1-c206-40e0-bf24-cbb55ca0cae9">
This is how it looked before the most recent system update - I'll fix the regression.

**Comment by Dorako** [comment]
Fixed in next release
