### ISSUE TITLE
Incompatibility with force client setting

### ISSUE THREAD

**Issue by BangBengBongBung** [Dorako/pf2e-dorako-ui#287]
![image](https://github.com/Dorako/pf2e-dorako-ui/assets/87244742/e23297e8-df2c-4c31-8d57-b7c235549d5e)
The only thing that bugs out is the roundedness slider

**Comment by Dorako** [comment]
I've deleted the migration code from the source, can you still reproduce this issue?

**Comment by BangBengBongBung** [comment]
![image](https://github.com/Dorako/pf2e-dorako-ui/assets/87244742/741e7f23-80be-48a7-b409-fe2ff8550862)
Sadly still happens, here are my configures the error is way up, shortly after the initiating of Your UI

**Comment by BangBengBongBung** [comment]
I found out if in the setting.js line 36 to 49 is removed everting works fine again

**Comment by Dorako** [comment]
Good to know.
I might add some logging to figure out which setting it is trying to find, but can't.

**Comment by Dorako** [comment]
I've moved the migration code to the bottom. This doesn't fix whatever the incompatibility is, but it should fix the roundedness setting not working.
