### ISSUE TITLE
Dorako UI was throwing a gigantic error on console every single time a token was selected or deselected.

### ISSUE THREAD

**Issue by sandersontavares** [Dorako/pf2e-dorako-ui#290]
![image](https://github.com/Dorako/pf2e-dorako-ui/assets/7301818/5ff4a26c-63c8-44e4-9e91-c08321b01b40)

I don't know how to explain better than this. It threw this error for every token in a scene when foundry started, then again once each time a token was selected or deselected. Tried using find the culprit and it pointed Dorako UI as being the reason and it was. I wil try to investigate further to find what module interaction was causing it.

**Comment by sandersontavares** [comment]
![image](https://github.com/Dorako/pf2e-dorako-ui/assets/7301818/9d84016b-500d-4614-9997-621c1bb309c0)
Running Find The Culprit with only Dorako Pinned still renders all these errors to the console on startup. But it does not render them when I select or deselect a token.

**Comment by Dorako** [comment]
I assume you're using some sort of module that is creating nonstandard chat messages - presumably some sort of turn markers?
That could explain the errors you see on startup. If something is happening when you select tokens, but not with just Dorako UI enabled, that is possible the module that also created the messages in the first place.

**Comment by RobertBeilich** [comment]
The error is not module depended. It shows up in a new world with only Dorako UI (and UX) enabled.
The default setting for Chat message headers is `Disabled` and with this setting, nothing is passed to https://github.com/Dorako/pf2e-dorako-ui/blob/54a885105e6aff51d867ba3558a497af48f71e47/esmodules/message-hooks.js#L74-L77 resulting in `headerColor` being undefined, when line 75 tries to access `substr`
