### ISSUE TITLE
Targeted Recall Knowledge from ITT is hard to read

### ISSUE THREAD

**Issue by cuyima** [Dorako/pf2e-dorako-ui#291]
When Dorako UI with is active, the font gets too large so skill names are cut off and the proficiency disappears. For any of the dark themes specifically, the row background is too light.
![image](https://github.com/Dorako/pf2e-dorako-ui/assets/52758909/dfad098b-3bb9-4e9e-86f4-0e4b79de779a) ![image](https://github.com/Dorako/pf2e-dorako-ui/assets/52758909/8be22654-0608-426e-9e0d-c4396c6401d5)

**Comment by Dorako** [comment]
![CleanShot 2023-12-12 at 00 28 42@2x](https://github.com/Dorako/pf2e-dorako-ui/assets/1561190/15bc7fe6-4829-4771-bfd0-67b515c62155)
Fixed for next release.

**Comment by Dorako** [comment]
Should be fixed in newest version
