### ISSUE TITLE
Reduce size of the headers in chat.

### ISSUE THREAD

**Issue by Fatalmac77** [Dorako/pf2e-dorako-ui#295]
Hi,
Is it possible to add an option to reduce the size of the headers in the chat? So that they are a little smaller and don't take up so much space?
![headers](https://github.com/Dorako/pf2e-dorako-ui/assets/128055466/ea039119-4000-4953-9558-57594559e653)

**Comment by Dorako** [comment]
You can disable the headers entirely if you want.
I don't think you can realistically trim more than a pixel or two of vertical height if you still want avatars to fit.
I used to have logic for moving the player name tags to the same line as the character name tag, if there was no avatar, but this was needless complexity, and looked real bad for long player names or long character names.
You're welcome to adjust the styling with custom css.

**Comment by Fatalmac77** [comment]
Thank you.
