### ISSUE TITLE
PF2 5.12 sheet updates causing hard to read elements

### ISSUE THREAD

**Issue by SoundSherpa** [Dorako/pf2e-dorako-ui#298]
After the pf2 5.12 updates to how language and speed are displayed on the sheet, the dark theme now has some issues displaying this data. Screenshot attached. 
![Screenshot 2024-01-06 204114](https://github.com/Dorako/pf2e-dorako-ui/assets/72993376/d1c02816-b2f5-475a-be8d-fc4fb4c61810)

**Comment by SoundSherpa** [comment]
Seems the NPC sheet has similar issues for Initiative, Saving Throws, Senses, and Skills as well. 
![Screenshot 2](https://github.com/Dorako/pf2e-dorako-ui/assets/72993376/571c6a5f-5737-4300-bde8-8e1edd503f2d)

**Comment by Dorako** [comment]
Fixed in 3.3.6
