### ISSUE TITLE
Issues with new NPC sheet css colors

### ISSUE THREAD

**Issue by MichalGolaszewski** [Dorako/pf2e-dorako-ui#299]
The colors seem to have been swapped in few cruicial places like:
saving throws 
![image](https://github.com/Dorako/pf2e-dorako-ui/assets/46850235/6df7e905-4f57-4c15-a990-094185dda16b)
rarity and size
![image](https://github.com/Dorako/pf2e-dorako-ui/assets/46850235/8aad2691-762c-4b12-8a22-ae2c127050c5)
skills and perception
![image](https://github.com/Dorako/pf2e-dorako-ui/assets/46850235/38a27f81-245f-4d1d-891f-012fcdeeee93)
spells and effects tabs
![image](https://github.com/Dorako/pf2e-dorako-ui/assets/46850235/61de15ad-69cf-487a-821c-2fdbccac515d)

making the text unreadable in the Player Core style (pale on pale background and the like)

**Comment by MrPrimate** [comment]
Also experiencing this, for context these are my theming settings:
![Screenshot from 2024-01-09 15-42-09](https://github.com/Dorako/pf2e-dorako-ui/assets/3985378/04073f8d-5898-4442-af08-b7fda5156962)

**Comment by Dorako** [comment]
Should be fixed in newest version (Remember to update UX as well).

**Comment by MrPrimate** [comment]
Thanks for the speedy fix!
