### ISSUE TITLE
No background for certain character sheet elements

### ISSUE THREAD

**Issue by WolffM** [Dorako/pf2e-dorako-ui#301]
![image](https://github.com/Dorako/pf2e-dorako-ui/assets/8714327/9b9e0793-c0f7-43b6-bce7-2c8fff4244e4)

**Comment by WolffM** [comment]
Notice Ancestry, Heritage, Background, Class, and Deity have no background.

**Comment by Dorako** [comment]
Hi, apologies for no response, I've been busy playing HSR.
Seems like .character-details was renamed to .subsection.details in a recent patch. Fixed for next release.

@FazeenIjaz You're always welcome to submit a PR.

**Comment by FazeenIjaz** [comment]
> ![image](https://private-user-images.githubusercontent.com/8714327/302811211-9b9e0793-c0f7-43b6-bce7-2c8fff4244e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2MjU4OTYsIm5iZiI6MTcwNzYyNTU5NiwicGF0aCI6Ii84NzE0MzI3LzMwMjgxMTIxMS05YjllMDc5My1jMGY3LTQzYjYtYmNlNy0yYzhmZmY0MjQ0ZTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTFUMDQyNjM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTI5NmZkY2Q5ODE2OWI5MTdiYzYzNTk5ZjBiMWIzY2ZmYWJiNzU3NTZlZTIxZDU2YTIwNDMyODVhNTM4M2YyNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.UBoigcsJoV-ypFVxFYyzgWw_wZUZ0Csw2JCWXhsQP3U)
@WolffM pls describe the steps to reach out to this issue
