### ISSUE TITLE
Sidebar width messes up Dice Tray etc.

### ISSUE THREAD

**Issue by ksignorini** [Dorako/pf2e-dorako-ui#303]
The width of the sidebar seems to have changed when Dorako UI is installed. As a result, the Dice Tray module's dice buttons don't fit anymore.

Default sidebar width is around 590 px
Sidebar width with Doraku UI is around 575 px

Can we get the width back please?

Thanks.

![image](https://github.com/Dorako/pf2e-dorako-ui/assets/6867660/f9503851-092b-4ed2-8778-3bc7490e075f)

**Comment by ksignorini** [comment]
You can do that?! How did I not know that? Wow!


--
Kent S.

**Comment by ksignorini** [comment]
> It's a feature of Dorako UX. You can also resize the chatbox.

Ah! OK, well then just note that the minimum size right now doesn't fit all the dice from Dice Tray correctly. Probably want to add a few pixels anyway.

Thanks again! Great themer!!!

**Comment by ksignorini** [comment]
Sorry to add to a closed issue... is there some CSS I could add to expand the minimum width a few points by default?

**Comment by Dorako** [comment]
What do you mean by default? Once you adjust the width it should save and you shouldn't have to adjust it again.

**Comment by ksignorini** [comment]
So that my players don’t all have to adjust it. Just what it starts at.


--
Kent S.
