### ISSUE TITLE
[Bug] Text on Tours in Dark Mode is Unreadable

### ISSUE THREAD

**Issue by ChasarooniZ** [Dorako/pf2e-dorako-ui#304]

**Comment by Dorako** [comment]
Gonna need some reproduction steps

**Comment by ChasarooniZ** [comment]
Okay so have a fresh Foundry install, Only Dorako UI + UX + PF2e ver `5.14.6`
Using following themes (manually copied from my normal game)
![image](https://github.com/Dorako/pf2e-dorako-ui/assets/79132112/c874ec72-3d37-4b4d-858f-7a0bababd85e)

1. Run Welcome to Foundry Virtual Tabletop Tour
2. Get To Step 2 of tour

![image](https://github.com/Dorako/pf2e-dorako-ui/assets/79132112/eb5f4484-cce1-4509-92b3-c77df5b98eba)

**Comment by Dorako** [comment]
Fixed for next release
