### ISSUE TITLE
[Enhancement] Spacing between chat cards

### ISSUE THREAD

**Issue by ksignorini** [Dorako/pf2e-dorako-ui#305]
Is there any way you could add an option to put  small extra space (maybe 5px) between chat cards? They're so jammed up together, it's sometimes hard to tell what's what.

From this:
![image](https://github.com/Dorako/pf2e-dorako-ui/assets/6867660/fcfd381b-ebe0-4c98-8c1e-0b93d3108363)

to this:
![image](https://github.com/Dorako/pf2e-dorako-ui/assets/6867660/63a212c6-74f6-4be0-9e1c-4f8bc96fd0a0)

**Comment by Dorako** [comment]
You can use custom CSS to change this exactly as you prefer, example:
```css
.chat-message:not(:first-child) {
    margin-top: 10px;
}
```
