### ISSUE TITLE
Attack box using dashed boundary

### ISSUE THREAD

**Issue by Ethan-Otto** [Dorako/pf2e-dorako-ui#308]
I'm using the most recent version of foundry, pf2e, and dorako-ui
I noticed my attach boxes are using this unpleasant dashed boundary. Anyway to to get back a solid boundary? 

![image](https://github.com/Dorako/pf2e-dorako-ui/assets/89815515/a58e4c48-0136-4aeb-82f6-95afe103b9d8)

**Comment by Dorako** [comment]
That is communicating information to you, namely that the contents of the box is hidden from players.
It is the same styling used for all gm-visibility elements.
You can restyle it with custom css if you please.

**Comment by Ethan-Otto** [comment]
Thank you so much
Would these be said elements?

![image](https://github.com/Dorako/pf2e-dorako-ui/assets/89815515/fca4d6cb-f866-47cd-88b3-43333822e7ec)

**Comment by Dorako** [comment]
That seems right - you're looking at compiled .css so those exact lines don't exist on my end.
