### ISSUE TITLE
Horizontal Rules does not work in journals using the Core Rulebook (light) Sheet theme

### ISSUE THREAD

**Issue by GillardMullek** [Dorako/pf2e-dorako-ui#310]
In Foundry v11.315 with Pafhinder 2e v5.15.0 system, all the **Horizontal Rules** had disappeared from all journals when using the **Core Rulebook (light) Sheet theme**. Horizontal Rules do not appear when we try to add them again, just a blank space appearing in their place.
Using the PF2e Dorako UX v1.3.6 and UI - PF2e Dorako UI v3.4.7.
![image1](https://github.com/Dorako/pf2e-dorako-ui/assets/166623751/a0e49df2-6172-4c34-a672-81d7ca4eef21)
![image2](https://github.com/Dorako/pf2e-dorako-ui/assets/166623751/eecfb8f2-6bc8-4d31-9fbc-bc4602f85ed3)

**Comment by Dorako** [comment]
They're still there, just transparent. I've added a color for next release.
<img width="650" alt="image" src="https://github.com/Dorako/pf2e-dorako-ui/assets/1561190/ca6db8a5-d5fb-4245-a061-f10ffb17ea16">
<img width="651" alt="image" src="https://github.com/Dorako/pf2e-dorako-ui/assets/1561190/c39366e8-8ce8-4ec6-8770-4f4c5aa53157">
