### ISSUE TITLE
Feature Request: Set Foundry UI Font

### ISSUE THREAD

**Issue by Armandeus66** [Dorako/pf2e-dorako-ui#311]
I would like to request the ability to set the Foundry UI font using Dorako UI, via the GUI.
I am currently using the custom CSS feature of the module settings to input this:
`:root {   --font-primary: IM Fell English; }`
...but I hear that is too aggressive, and I would rather trust Dorako with the setting, if possible, because I think there would be less problems than with my method.

**Comment by Dorako** [comment]
I don't have any plans for something like this, and if I had, I would be doing variable replacements exactly like the one you're doing in custom css already.
You might need to adjust the font size if the font you're using is particularly small or large.
