### ISSUE TITLE
Vehicle sheet color styling not respecting settings

### ISSUE THREAD

**Issue by MattOutfusion** [Dorako/pf2e-dorako-ui#312]
It always appears red with a light background making it impossible to read field headers and doesn't seem to be able to be changed at all.

**Comment by MattOutfusion** [comment]
![image-9.png](https://github.com/Dorako/pf2e-dorako-ui/assets/101127517/470aacc8-af3c-48c4-b7f9-94e66af2a9fd)

**Comment by Dorako** [comment]
Fixed in next release
