### ISSUE TITLE
[Bug] Vaux’s Archives Search Bar text not visible on dark mode

### ISSUE THREAD

**Issue by Peach774** [Dorako/pf2e-dorako-ui#313]
Reproduction steps:

1. Create a chat archive using Vaux’s archives, make sure you are using crb dark mode for everything.
2. View the archive
3. Type anything into the search bar within the archive you are viewing
4. The text you typed will be the same color as the background bar you are typing into and won’t be visible.

**Comment by Dorako** [comment]
Fixed in next release
