### ISSUE TITLE
Many labels/tabs become buttons, resulting in UI/aesthetic issues

### ISSUE THREAD

**Issue by Kosyne** [Dorako/pf2e-dorako-ui#315]
Foundry: 11.315
PF2e Dorako UI: 3.4.10
PF2e Dorako UX: 1.3.6

In many places in the default theme, clickable lables more or less represent tabs, such as here in the NPC character sheet:
![firefox_8685IGH0AR](https://github.com/Dorako/pf2e-dorako-ui/assets/356616/86ca261e-b29a-4815-9d29-989a9428e06e)

However, Dorako UI globally turns these into buttons, which can look off depending on the page, and the button's borders often conflicts with neighboring elements, or the spacing between buttons may look odd, particularly in places where the visual intent was for 'tabs' not 'buttons'. At best it may look 'too busy' or 'off', and at worst, you'll have clipping or a less than ideal look.

Examples:
![image](https://github.com/Dorako/pf2e-dorako-ui/assets/356616/023e6694-b303-4a8a-846a-2b05eb6f3838)
![firefox_zGuusaNp08](https://github.com/Dorako/pf2e-dorako-ui/assets/356616/d9c4030c-f83c-4e55-81a4-964aafb27d05)
![firefox_2tY1oQEt5J](https://github.com/Dorako/pf2e-dorako-ui/assets/356616/d42a0c52-7a17-493b-bec8-3d6f56d9f7fc)

You can see here that it hits 3rd party modules particularly hard:
![firefox_nTSPbFrC9e](https://github.com/Dorako/pf2e-dorako-ui/assets/356616/15217fe4-eb72-44cf-87c7-4a42f9927044)
![firefox_41jqAGG3IK](https://github.com/Dorako/pf2e-dorako-ui/assets/356616/7703b88d-d9a7-4123-9176-7f210bfb4e8e)
![firefox_2tc1WouqLt](https://github.com/Dorako/pf2e-dorako-ui/assets/356616/c823f07e-8f40-4e20-b9ea-7e823318d7a1)
![firefox_lY81bMXm4M](https://github.com/Dorako/pf2e-dorako-ui/assets/356616/79d40d9c-211b-4573-b6c1-96443d87e561)

Admittedly, this screen in particular looks just fine as buttons:
![image](https://github.com/Dorako/pf2e-dorako-ui/assets/356616/790a7523-5cbe-46ca-b8a3-fae9b3965e50)
![image](https://github.com/Dorako/pf2e-dorako-ui/assets/356616/6407e27e-d47d-49b7-bee4-ea55cfbada99)

### Proposal
Let these areas return to being labels, or perhaps a new style to represent 'tabs'. At the very least, it would be nice to have an option to keep Dorako UI minus the button style.

**Comment by Dorako** [comment]
The reason it's like this is because it allows for standardisation across multiple themes. If I don't touch the labels at all, you end up with unreadable text on themes with darker backgrounds etc.
By restyling them as buttons, I'm sure they're legible, since the buttons are designed to fit with the theme, and are legible on the background provided by the theme.
If you're only using one specific theme, you can use custom CSS to make a localized change in the nav tabs scope to restyle the --button series of variables (check the [Wiki](https://github.com/Dorako/pf2e-dorako-ui/wiki/Theme-Variables)) to suit your preferences.

**Comment by Kosyne** [comment]
Thanks for the quick response!

In trying to fit with the theme, it introduces quite a few inconsistencies, no? I'm aware I could style it back, but some of those examples above were kinda jarring and didn't seem intentional so figured I'd at least bring it to your attention.

**Comment by Dorako** [comment]
It's a compromise, but it's what allows almost everything to be compatible with ~5-10 significantly different themes out of the box, with me only rarely having to add styling specifically for modules that I've never used or heard about.
As for the margins in the system item sheet, I've added some padding to avoid clipping.
