### ISSUE TITLE
Confirmation dialog on "Save Module Settings" 

### ISSUE THREAD

**Issue by S-North** [Dorako/pf2e-dorako-ui#317]
Text colour on the confirmation of save module settings dialog is no correct.
![image](https://github.com/Dorako/pf2e-dorako-ui/assets/8228899/8e08e6cb-4f17-43b7-85ad-00a494392feb)

Foundry: 12.327
pf2e: 6.0.1
doraku: 3.5.1

**Comment by Dorako** [comment]
Should be fixed in one of the recent versions
