### ISSUE TITLE
Right Sidebar UI too big

### ISSUE THREAD

**Issue by JamalBumbey** [Dorako/pf2e-dorako-ui#319]
As mentioned in the title, the Icons on the top of the Sidebar on the right is too big and is shoved out of view
![uhm](https://github.com/Dorako/pf2e-dorako-ui/assets/172655860/53550652-0af5-493d-a311-e14055f3386b)
Reference picture ^

**Comment by Dorako** [comment]
I can't reproduce this, have seen nobody else report it, and the sidebar code has not been touched for a while.
Try running find the culprit to determine the specific modules that are causing this - it doesn't look like you're using Dorako UI in the picture (possibly UX though), or you have certain settings disabled.
