### ISSUE TITLE
Request: Monk's Player Settings Compatibility

### ISSUE THREAD

**Issue by MrZeyami** [Dorako/pf2e-dorako-ui#320]
Would love to see the settings saving not just locally so I can pick a consistent look for my games, and also so players dont have to remember their settings on another device.

**Comment by Dorako** [comment]
Yeah it's pretty weird that foundry client settings work like that, but you can use a module like Force Client Settings, and I believe Monk has a module that does something similar as well.

**Comment by MrZeyami** [comment]
I couldn't find any other Monk module with that functionality but Force Client Settings seems to be working. Thank you.
