### ISSUE TITLE
Is the SASS folder and sub-folders/files supposed to be included in the release package installed in foundry?

### ISSUE THREAD

**Issue by Truncated** [Dorako/pf2e-dorako-ui#325]
I've been exploring the possibility of adding two other modules to the supported list. While I was poking around for that, I noticed that the foundry source console shows the SASS folder and all of the sub-folders/files as if they should be in the module directory, but they are all 404 errors instead as they were not included in the release package.

When I added the folder from the source zip to my module directory, everything seemed much smoother and a bit quicker.

I certainly can't tell you if it's the folder _should_ be included and it wasn't or references are somewhere that need to be removed because the creation of the release handles that code a different way, or whatever else, but generally I figure if its looking for something it should be there so that's what I did and what I experienced, fwiw.

**Comment by Dorako** [comment]
I think I included this some time ago, let me know if I'm wrong
