### ISSUE TITLE
Feature Request: Disable Chat Portrait Enlarge on Hover

### ISSUE THREAD

**Issue by OutlandishVillainy** [Dorako/pf2e-dorako-ui#33]
The portraits in the chat are really nice, but me and my players think it would be better if you could disable the portraits enlarging when you hover over them, especially since it can be a bit buggy.

https://user-images.githubusercontent.com/93902659/158054504-cd995c1b-9fd1-46c7-94a7-7bd439dd1297.mp4

**Comment by Dorako** [comment]
It works much more reliably if you mouse in from the left. I do agree it should be optional though. Ideally when enabled it should just scale, rather than translate and scale, which is what is causing the issue in your video, but is necessary right now or the image gets cut off.
