### ISSUE TITLE
[BUG] Duplicated token header

### ISSUE THREAD

**Issue by Kronos25** [Dorako/pf2e-dorako-ui#334]
After updating i'm seeing a duplicate icon on header breaking the visuals on chat:

Foundry: v12.330
PFE: v.6.3.0
Dorako UI: v.3.5.11
Dorako UX: v.1.4.3
![image](https://github.com/user-attachments/assets/ae93699a-9884-468f-9941-2927dd435f2c)

**Comment by Dorako** [comment]
Try updating modules real quick

**Comment by Kronos25** [comment]
Everything seems fine now, thank you for the speedrun fix! :D 
![image](https://github.com/user-attachments/assets/e20cd4a3-d4a3-4764-b4d6-d1e276d43d5d)
