### ISSUE TITLE
[BUG] Sheet theme not applying

### ISSUE THREAD

**Issue by Kronos25** [Dorako/pf2e-dorako-ui#335]
I know I just reported a bug and closed it as solved, but I noticed a new one a couple of moments after the new update (UI v. 3.5.12 // UI v. 1.50)

When selecting a theme for the character sheet, it doesn't seem to apply and defaults to the light theme
![image](https://github.com/user-attachments/assets/30f39365-89cf-4745-a972-7597b9822b66)

**Comment by Dorako** [comment]
I can't reproduce this.
![CleanShot 2024-08-30 at 03 23 13@2x](https://github.com/user-attachments/assets/3cb56a9b-cb09-4899-b8de-9315f498836b)
Are you using the starfinder module?
Are you sure a theme is applied at all, or is it just the stock foundry look? (Check the titlebar)

**Comment by Kronos25** [comment]
I'm using the Pathfinder module/system
![image](https://github.com/user-attachments/assets/d9f0f8b8-a57d-4d5f-9d3a-94172a0ccc80)

I'm almost sure it's applying the theme (or supposedly to), I've tried changing it to other combinations, but now that you mentioned related to the title bar, it seems somewhat related to the stock foundry look. Not sure what is going on
![image](https://github.com/user-attachments/assets/bdbe6bfd-299d-432d-8c90-c12a981532d4)
![image](https://github.com/user-attachments/assets/0f16f0b3-2adf-4a3c-ad56-cf92524eb692)

**Comment by Dorako** [comment]
Yeah so what I'm seeing is that no theme is getting applied for that sheet, which is typically because it's been excluded, or because the theme system is crashing. (Check for red console logs).
I've put out an update, see if that fixes it for you.

**Comment by Ethmaker** [comment]
I am getting the same issue with the update. Here's the console error that is showing up for me:
![image](https://github.com/user-attachments/assets/9c63027b-8ee2-4851-9594-0e4270cbb6eb)

**Comment by Kronos25** [comment]
It seems to be working for me now, thanks :)  
I'll leave the topic open for now to make sure it's also solved for @Ethmaker and others 
![image](https://github.com/user-attachments/assets/ee2671f2-ec10-46a1-9452-df7e07530795)

Thank you!

**Comment by Ethmaker** [comment]
After updating modules again and reloading the world, the issue seems fixed and themes are properly working again.

**Comment by 8bitjunkie** [comment]
![image](https://github.com/user-attachments/assets/1a4b22d7-6169-444d-9928-d8434322658e)
Here is the error; I have a similar problem - all updated system and Dorako mods.

**Comment by Dorako** [comment]
I see the issue, should be fixed for next release.
