### ISSUE TITLE
[BUG] Setting Interface Theme to "No Theme" still change sidebar

### ISSUE THREAD

**Issue by farling42** [Dorako/pf2e-dorako-ui#339]
With the Interface Theme set to "No Theme".

The element inspector shows that a style is still being applied to the sidebar.

```
[data-dorako-ui-scope=sidebar] .tab:not([data-tab=chat])
```

My UI settings:
![image](https://github.com/user-attachments/assets/5b016c1d-8a50-45a2-bed6-a62394e89d70)

**Comment by farling42** [comment]
But the CSS I quoted specifically excludes the chat tab, and it is affecting all the other tabs.

**Comment by Dorako** [comment]
I see what you mean, there's a couple of styles in _sidebar that is using [data-dorako-ui-scope=sidebar] where they should be using [data-chat-interface-theme].
Fixed for next release.
