### ISSUE TITLE
Centre hotbar

### ISSUE THREAD

**Issue by roguedevjake** [Dorako/pf2e-dorako-ui#34]
The centre hotbar option seems to have broken with the last update.

**Comment by Dorako** [comment]
<img width="1576" alt="image" src="https://user-images.githubusercontent.com/1561190/159160874-b3a61700-da34-491f-8845-6534b91eb39a.png">
I can't reproduce this

**Comment by roguedevjake** [comment]
> I can't reproduce this

I am using:
- Windows 10
- FoundryVTT v9.255
- Dorako v1.3.11 (just reinstalled to be sure)
- PF2e v3.7.2.10819

World is a fresh world, only module enabled is dorako ui and it still does it.

Will try a fresh foundry install to see if it is something going on on that side.

**Comment by roguedevjake** [comment]
Update:
Fresh install of foundry vtt worked. Backup restored and bar was centered.
