### ISSUE TITLE
Bug: Dorako UI making a few popups unreadable

### ISSUE THREAD

**Issue by MothMariner** [Dorako/pf2e-dorako-ui#341]
Not sure on the descriptor for the specific type of popup, but it's the one that appears when it asks to reload the application.

Steps to recreate: 
Mac system needs to be in dark mode (Chrome browser dark or light does not affect the result, only system dark or light).
Have Dorako UI on.

Looks like this
![Screenshot 2024-10-06 at 23 25 57](https://github.com/user-attachments/assets/10afbe01-6a2e-4b6e-8bad-33ec3f8538cd)
Made using Find the Culprit kinda hard 😅 
![Screenshot 2024-10-06 at 23 43 23](https://github.com/user-attachments/assets/284f6763-253e-429a-b3d0-95b3293b7fdf)

Dorako UI 3.6.1
FVTT 12.331
PF2e 6.4.1
MacOS Sonoma 14.7

**Comment by moarx** [comment]
Same issue here currently with the same popups and possibly a few others - I encountered it a handful of times when GMing last night, will have to play around to pinpoint exactly which windows it was.
Running on Windows with the latest versions of Dorako UI, FVTT (via Forge), PF2e, Chrome. System is in Dark Mode but I typically use Core Rulebook (Light) theme. If I switch to dark the text color is light and thus visible but I prefer the Light sheets.

**Comment by Dorako** [comment]
Should be fixed now, can you confirm?

**Comment by MothMariner** [comment]
Winner, it works! Thank you for your service 🫡
