### ISSUE TITLE
PF2e HUD Colorize Token HUD

### ISSUE THREAD

**Issue by RisingStarPF2e** [Dorako/pf2e-dorako-ui#342]
_The new compatibility with PF2e HUD over the old ITT (Colorize) the new compatibility is only colorizing the on-hover but not colorizing the Token Hud panel when you click on a token/don't use the persistent hud. I tried all groupings and none of them are effected rn. Groupings are effected by the "Display Mode" setting in PF2e HUD._

_**Ideally; these should be colored the same.** I've missed this feature so much and this helps me coordinate a lot better! Would love to see the Hero Points, Dying/Wounded being colored as they use to with the ITT implementation._

- **On-Hover (Correct):**

![image](https://github.com/user-attachments/assets/db792a0c-78fd-4099-8555-23da4a51cdae)

- **Grouped Right:**
![image](https://github.com/user-attachments/assets/8883a9b4-29a8-414e-a019-551d47644db1)

- **Exploded:**
![image](https://github.com/user-attachments/assets/78dfca0b-0c69-4fea-98c5-e0a2c7b2d576)

- **Grouped Left:**
![image](https://github.com/user-attachments/assets/fd389c12-253b-45e7-b2d0-a26b7e643ed9)

**Comment by Dorako** [comment]
For the next version I've added theme support for the 'grouped' view (which was entirely missing) and made the colored icons affect the other tooltip modes as well:
![CleanShot 2024-10-17 at 18 59 21@2x](https://github.com/user-attachments/assets/afa61fea-35e1-441d-b976-dc7eee1536d2)
As for recoloring specific icons, I recommend using custom css like this:
```css
.pf2e-hud i.fa-notes-medical {
    --icon-color: goldenrod !important;
}
.pf2e-hud i.fa-tombstone {
    --icon-color: orange !important;
}
```

**Comment by RisingStarPF2e** [comment]
Such a chad. You even added some support for See Simple Scale Stats! <3
