### ISSUE TITLE
Huge performance loss when used alongside pf2e-hud's Persistent HUD

### ISSUE THREAD

**Issue by ThePhxRises** [Dorako/pf2e-dorako-ui#345]
[Issue also filed with pf2e-hud](https://github.com/reonZ/pf2e-hud/issues/48)

Setting up a new campaign and as I was going through and enabling my usual set of modules, I noticed that having pf2e-doraki-ui enabled with a theme applied alongside the Persistent HUD from pf2e-hud causes a *massive* performance loss. On my system I go from a steady 165 (my refresh rate) to somewhere between 50 and 80. Disabling either module or the theme/persistent HUD in settings resolves the performance loss.

On further analysis it seems this performance loss also happens with the Persistent HUD disabled when either of the Token HUDs are drawn, seeming like it occurs with any UI drawn by pf2e-hud

I would have assumed these two modules worked together given Dorako UI has a setting specifically for theming the HUD, but it would seem not. Is this a new issue?

I was going to try and add pf2e-hud to the Excluded Applications list but I can't figure out which identifier from the logs to use for it.

**Comment by Cthoodles** [comment]
You still experiencing this issue? I was thinking about trying PF2e HUD but I'm worried it might cause problems with this module

**Comment by Dorako** [comment]
PF2e HUD is great, highly encouraged

**Comment by ThePhxRises** [comment]
> You still experiencing this issue? I was thinking about trying PF2e HUD but I'm worried it might cause problems with this module

It seems to have been fixed in an update to pf2e-hud.
