### ISSUE TITLE
[Feature Request] Option to make chat message headers correspond to the color of the relevant actor's owner, instead of the message's source

### ISSUE THREAD

**Issue by Cthoodles** [Dorako/pf2e-dorako-ui#346]
When using the colored chat message header option with the core rulebook message themes, I appreciate having the option to make the headers match the color of the assoicated player. This creates some mismatches on occasion, though- for example, when a module like PF2e Toolbelt auto-rolls recovery checks for persistent damage, the header is always in the color of the GM, not the color matching the player whose actor is rolling the recovery check. It'd be nice to have the option to match the colors to the actor's owner, for consistency's sake

**Comment by Dorako** [comment]
Does it work like how you imagined it in the latest version?

**Comment by Cthoodles** [comment]
It does! Thank you.

I think I'm getting some lag spikes now whenever it does the automatic persistent damage roll though. Not sure if that's from this module or something else
