### ISSUE TITLE
Update: Hotbar Centering

### ISSUE THREAD

**Issue by roguedevjake** [Dorako/pf2e-dorako-ui#35]
Issue previously referred to in issue([34](https://github.com/Dorako/pf2e-dorako-ui/issues/34))

The problem that causes the bar to not be centered is tied to the theme app ui setting, when turned off (and the session refreshed/reloaded) the hotbar is no longer centered despite still being themed.

(I turn it off normally because of less desirable style interactions with filepicker+)

**Comment by Dorako** [comment]
I will look into this (at some point!)

**Comment by Dorako** [comment]
https://github.com/manuel-hegner/foundry-filepicker-favorites
Is this the module you are talking about? (I realize that wasn't your main issue)

**Comment by roguedevjake** [comment]
> https://github.com/manuel-hegner/foundry-filepicker-favorites Is this the module you are talking about? (I realize that wasn't your main issue)

Nah filepicker+ is a paid module by theripper93, the issue was that the text would be unreadable with the themed app ui settings. But I fixed it by not being lazy and a CSS override.

https://streamable.com/ql2x55

If you aren't already using it and GM I highly recommend the module though, it and image context both modules I wouldn't do without anymore.

**Comment by Dorako** [comment]
Think I fixed this
