### ISSUE TITLE
Buttons near the top hard to click on (with forge hosting, which normally pushes the toolbox down)

### ISSUE THREAD

**Issue by Bastlifa** [Dorako/pf2e-dorako-ui#37]
So, without the mod on, the Foundry icon pushes the toolbox on the left down, and all of the buttons work normally. With Dorako UI, the Foundry icon is missing, and the top 2 rows of the toolbox have a tiny section that's clickable (worse for the topmost row). 

Without DorakoUI:
![image](https://user-images.githubusercontent.com/19656160/161873241-5968c3c1-71d3-4f4a-840a-b0a66e04f983.png)

With DorakoUI:
![image](https://user-images.githubusercontent.com/19656160/161873375-a9f56a9a-450a-4be1-83cb-ae79945a427e.png)

Tiny spot at the top:
![image](https://user-images.githubusercontent.com/19656160/161873417-79d608d0-52dd-44f0-90ac-aaf95a50d0a0.png)

**Comment by Dorako** [comment]
I believe there's a setting for whether to hide or show the foundry logo?

**Comment by Bastlifa** [comment]
Oh, I see it now. I was looking for Dorako, not PF2E Dorako in the settings list. Just tried, and it works fine with the logo shown.
