### ISSUE TITLE
Add an option to use Actor image for chat portrait always

### ISSUE THREAD

**Issue by medeiros3010** [Dorako/pf2e-dorako-ui#46]
Currently, the image that appears in the chat is the Token, not its portrait. People who use the "top view" token make using this feature a bit awkward.
If possible, add to show the portrait of the players/creatures in the chat
![image](https://user-images.githubusercontent.com/105553320/168430082-9e3309e4-59f5-4d21-9dc5-d4cbcd238b5e.png)

OBS: I noticed that when I'm not with the actor in the scene, he uses the portrait instead of the token, as shown in the image below
![image](https://user-images.githubusercontent.com/105553320/168430114-39b16308-0f31-4560-b15b-bede78f6e705.png)

**Comment by Dorako** [comment]
Will look into it!

**Comment by Dorako** [comment]
Next release will have a toggle for different types of chat portraits. Additionally if you use https://foundryvtt.com/packages/combat-tracker-images it will prefer those images (So you can make special images for your players and stuff)
