### ISSUE TITLE
Token distinction being invisible

### ISSUE THREAD

**Issue by medeiros3010** [Dorako/pf2e-dorako-ui#47]
It is very difficult to distinguish in the icon "anterior visibility" if it is active or not. If you look at the token, you can see it, but some tokens that are more translucent, or that are in scenes with fog, make this mission impossible.
Idea: Annotate the color for when it's invisible and when it's not
![image](https://user-images.githubusercontent.com/105553320/168444230-b36a5ba8-3702-4eec-9a76-d4ef01e9c37b.png)
Invisible
![image](https://user-images.githubusercontent.com/105553320/168444237-586b8023-fa02-4248-a8b3-1c98f443317d.png)
normal

**Comment by Dorako** [comment]
You are using a module that changes the invisibility icon. The stock looks like this:
<img width="266" alt="image" src="https://user-images.githubusercontent.com/1561190/168462153-453ff751-60bf-4d7f-8e8d-e168b03e8215.png">
<img width="281" alt="image" src="https://user-images.githubusercontent.com/1561190/168462171-7db8b522-5922-4253-afca-1869974f1c98.png">
