### ISSUE TITLE
Feature Request: Adjustable Padding

### ISSUE THREAD

**Issue by Bolt7** [Dorako/pf2e-dorako-ui#5]
It'd be great to remove or lower the padding you added in chat card text. It hides up to 1 small chat card, which is a lot considering how few the chat already shows. Either a slider, toggle, or change to the default would be much appreciated.

Two more things:
1. Fantastic module. Love the look.
2. It is I, the person who pushed for 2e module name unification, resulting in more of the chaos I sought to reduce (both Pf2E and pf2e were first used as pushback). My cruisading days are over, and I come not with a sword, but a plea: please consider using the PF2e naming scheme that 26/34 (~75%) use, or at least the more common PF2E that 5/34 (~15%) use. If it goes against your wishes, I will mention it no further.

**Comment by Dorako** [comment]
I love the evidence-based approach. I will conform to the PF2e naming convention. Any stats on whether it should be "PF2e Dorako UI" or "PF2e - Dorako UI" or similar?
I will be providing options for changing all of the offsets in a user-friendly way. I've posted a pic on the discord thread of a version with much less empty space, check if you prefer that.

**Comment by Bolt7** [comment]
Thanks for considering! The stats for dashes are 3/34 (9%) with, and 31/34 (91%) without. Or if you look at it from a different angle, 2/2 (100%) of the modules where the next word is the creator's name/tag. Frankly my goal isn't to standardize every aspect of the module name, so I don't want to put any pressure on this issue.

I looked at the thread, and there are a lot of cool ideas, but I couldn't find the condensed image. Look forward to the options, and thanks for your time making this module!

**Comment by Dorako** [comment]
@Bolt7 I'm continually tweaking padding and margins, if you see anywhere you'd like to shrink in a "dense mode", please include a picture so I can have a look

**Comment by Bolt7** [comment]
Sure. This is what I my personal change would be. It lets you see more, and still looks far from cluttered imo.

Before (padding: .5em)
![image](https://user-images.githubusercontent.com/75871317/152626415-479a3d6a-bffb-4ad3-a7d9-f03584fb1ab1.png)

After (padding: .1em)
![image](https://user-images.githubusercontent.com/75871317/152626436-9dcf8cdc-79ef-4031-a870-2a3af5964bad.png)

**Comment by Bolt7** [comment]
Noticed the changes. They're fantastic! It looks much better, and I have no doubt it'll improve even more. If it had to say one thing it's that the Token Action HUD spell buttons could use 1-2 more pixels of room on the right. As it stands the letters scrape the edge. But really, stellar work.

Because the padding has been reduced, I'm going to close this issue, since an adjustable value isn't really necessary now imo. The default is great.
