### ISSUE TITLE
Links Difficult to read using Dark theme

### ISSUE THREAD

**Issue by terrulin** [Dorako/pf2e-dorako-ui#50]
The default dark red which works great for the Light Theme is tough to read on the Dark theme.
Perhaps the CSS value for "color" could be changed for "a" when the dark theme is selected?
![link](https://user-images.githubusercontent.com/27816675/169092782-1fa627b8-70cb-4641-b485-4c22da28ff87.png)

**Comment by Dorako** [comment]
How does one post a link in a chat message?

**Comment by terrulin** [comment]
Awesome, thanks!
