### ISSUE TITLE
DF Chat Enhancements "show who is typing" function hides chat

### ISSUE THREAD

**Issue by grankless** [Dorako/pf2e-dorako-ui#53]
https://i.imgur.com/m5Jx7sv.png

This seems to be happening since that chat card modification? It wasn't happening prior to the update, though I don't really have any confirmation on that. It covers up just a little bit of the chat. It's not like big but it's annoying.

**Comment by Dorako** [comment]
Interesting, I can't think of why that would impact that. Did DF Chat Enhancements update recently?
I also can't find the setting that enables 'show who is typing'.

**Comment by MrVauxs** [comment]
It's Cautious Gamemaster's Pack btw, it would be great to see this fixed as the jittering and half-hidden messages can be quite distracting.

**Comment by MrVauxs** [comment]
Found the issue, it's `min-height` in `chat-form textarea`
https://cdn.discordapp.com/attachments/938840774357970967/1045660911832158218/W3fGvfEGnr.mp4
