### ISSUE TITLE
Inverted Icons

### ISSUE THREAD

**Issue by launqistormfist** [Dorako/pf2e-dorako-ui#54]
Dark mode is inverting the status effect icons in the chat log.

**Comment by Dorako** [comment]
<img width="317" alt="image" src="https://user-images.githubusercontent.com/1561190/170301194-218206cf-cef8-4ccb-be28-eb54dd2bbddd.png">
I'm not seeing this - or are you referring to something else?

**Comment by launqistormfist** [comment]
![image](https://user-images.githubusercontent.com/69098284/170580350-a5310f54-e2af-46bf-b0b7-1b5b7d2914da.png)



I'm using a roll table with status effects in it

**Comment by Dorako** [comment]
Fixed for next release. I know I added the inverting for a reason, but I can't recall it anymore.
