### ISSUE TITLE
Breaks on a foundry instance with a route prefix

### ISSUE THREAD

**Issue by Felerius** [Dorako/pf2e-dorako-ui#55]
The absolute image urls in the css files fail to load when using a foundry instance hosted at a sub path (e.g., `https://my.domain/my/prefix/`). As an example, the chat background image fails to load. There might be other things breaking but that's the one I noticed. Foundries own css files seem to get around this by using relative paths everywhere.

**Comment by Dorako** [comment]
Ah interesting, I went for fully qualified paths for reasons that no longer matter, so I should be able to move over to relative paths without issue

**Comment by Dorako** [comment]
Once you've updated, can you report back whether it works now?

**Comment by Felerius** [comment]
Thanks for getting around to this so quickly! There's still one absolute url in `familiar-sheet-dark-red-header.css` that I can get to break when testing. There's various others in `-trim.css` files, but I guess they are not being used right now?

**Comment by Dorako** [comment]
Ah, I'll tell Vesselchuck, he is maintaining the PC and Familiar dark sheet styles. Yeah the trim files are unused - they're part of an experiment where I totally annihilate all foundry styling and redefine only the parts that I like - not really suitable for a wide audience.
