### ISSUE TITLE
Bug: Monk's Hotbar Expansion

### ISSUE THREAD

**Issue by roguedevjake** [Dorako/pf2e-dorako-ui#57]
Tooltips and right click context menus appear under the expanded rows if the custom styling is applied, requiring the rows to be minimized to make any changes (normally they appear over the expanded rows when the custom styling is not applied)

**Comment by Dorako** [comment]
> Tooltips and right click context menus appear under the expanded rows if the custom styling is applied, requiring the rows to be minimized to make any changes (normally they appear over the expanded rows when the custom styling is not applied)

I don't use this module myself, if you could take a pic of broken and working behaviour, it'll be easier to fix.

**Comment by Dorako** [comment]
fix'd in next version.
