### ISSUE TITLE
Request: Character Sheet Colors

### ISSUE THREAD

**Issue by Armandeus66** [Dorako/pf2e-dorako-ui#62]
1. I like the dark character sheet option, but there are a few places (like the blue text for the character's primary ability score) where things are hard to read. Could we have an additional option for a bit less dark background, or could the dark sheet adjust these text colors to be more legible?

2. Could we have a new option that uses the Foundry player color instead of dark red on the ribbon on the left and at the top of the sheet? The dark red familiar sheet could use the master PC's player color.

Thanks!

**Comment by Vesselchuck** [comment]
1. I understand that there may be some problems with individual colours, so I am always willing to make changes by replacing the current colours with suggested colours. Of course, the problem here is that someone needs to suggest colours. I'm not much of a designer, to be honest, so for me even what I have now isn't bad. Nevertheless, as I said, always open to suggestions for a colour palette!
2. It's possible, but it'll probably need Dorako's helping hand, I'm not sure how he does it with the headers in the chat.

**Comment by Armandeus66** [comment]
Thanks for responding!
As far as chat is concerned, I use the light theme which shows player colors on the chat blocks and I am satisfied with that.
I was referring to the Pathfinder 2E player character sheets.
I will post some screenshots here to explain what I was talking about.
The suggestion about player colors was simply to take the color assigned to the player in Foundry that owns the character sheet and use it as the top bar and left banner color.
Here is a link to the screenshots.
https://imgur.com/a/lPTvcgK
In the first one, you can see the blue text for the primary attribute (in this case, wisdom). I was wondering if the color could be lightened for the dark theme so the score and the text above it is easier to read.
In the second screenshot, the colors are fine, but maybe we could have a bit of space between the number and the skill name.
Otherwise, I really like the dark theme.

**Comment by Vesselchuck** [comment]
I'll try some colour ideas and do an update for the Dark PC Sheet soon. Regarding the problem with the lack of space between the skill modifier and its name. I'm assuming that the issue here is that you've adjusted the text enlargement in Foundry.

**Comment by Vesselchuck** [comment]
And as for changing the colour to match the player's colour, that's probably too complicated for me. Forgive me, but personally I'm not prepared to introduce such an option.

**Comment by Dorako** [comment]
Closed after merging Vesselchuck's changes
