### ISSUE TITLE
Customize Token Scale

### ISSUE THREAD

**Issue by MrVauxs** [Dorako/pf2e-dorako-ui#67]
So the pop-out update got me hooked on trying out Dorako UI and I love how much it improved since last time I tried it.

There is one issue with this update though, it's hard-coded to only allow pop-out tokens that are equal or higher than `1.5` in their scale. All of my tokens that I use and create are in `1.4` scale.

https://github.com/Dorako/pf2e-dorako-ui/blob/db86231a9d9222becebcf354e01376a64ee4f3ac/scripts/dorako-ui.js#L221

It would be great if it was customizable. Might even go a Pull Request for the sake of expediency...

**Comment by Dorako** [comment]
Made redundant by the new implementation
