### ISSUE TITLE
Incompatibility with Chat Message Timestamp module

### ISSUE THREAD

**Issue by Ghostdesu** [Dorako/pf2e-dorako-ui#70]
**Describe the bug**
Using any setting other than foundry default seems to make the chat portrait added by Dorako UI disappear.

**To Reproduce**
1. Install PF2e Dorako UI and Chat Message Timestamp 
2. Enable both of them in the same pf2e world.
3. Set Chat portrait style setting to any option other than Disable.
4. Set Show date setting to any option other than Foundry
5. Send an in character message in chat (for example using one of the pregenerated characters from the included compendiums)

**Expected behavior**
A portrait based on the actor image or token should be visible in the message header.

**Screenshots/GIFs/Videos**
Show date: Foundry
![image](https://user-images.githubusercontent.com/31375910/180031431-e9c47dd3-00f4-4e5a-bba6-c4a8c65b6614.png)

Show date: Always
![image](https://user-images.githubusercontent.com/31375910/180031203-eb9353c6-cc24-494c-b7a6-27de50021177.png)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox
 - FVTT Version: 9.269
 - Chat Message Timestamp version: 0.2.0
 - PF2e Dorako UI version: 1.4.2

**Notes**
Currently I am using Chat Portrait module as a workaround (it's not as pretty though), so maybe looking into how it handles this could be helpful.
I am also reporting this at https://github.com/jsavko/chat-timestamp/issues/6

**Comment by Dorako** [comment]
The 1.5 refactor incidentally fixes this incompatibility.
