### ISSUE TITLE
Player avatar does not get used as chat portrait

### ISSUE THREAD

**Issue by Ghilteras** [Dorako/pf2e-dorako-ui#71]
Hi, I have a game master icon assigned, but when I do something in the chat the icon does not show. This is on Forge.

It works if I enable chat portraits module though

Latest stable version of Foundry and latest version of the module

**Comment by Dorako** [comment]
The module doesn't currently look for what foundry calls a 'user avatar' (which can also be configured for game masters).
I made a version where it does look for that, but I'm not sure if it should *only* look for that for gamemasters? Seems to me that it'd be pretty confusing to default to some image for a player if they type something without having anything selected.

**Comment by Ghilteras** [comment]
I think doing it for GMs only would be good enough

**Comment by Ghilteras** [comment]
@Dorako I think doing it for GMs only would be a good solution because players can still get their token portrait/image anyway so once we fix it for GMs the problem just goes away

**Comment by Dorako** [comment]
That was my thoughts as well - I implemented it for next release
