### ISSUE TITLE
Request: Make "Gold and Glow" box shadow optional

### ISSUE THREAD

**Issue by janouna** [Dorako/pf2e-dorako-ui#75]
In v1.5.2 a gold box shadow was added to all the windows and chat messages in dark mode. Can a toggle to enable/disable the shadow be added to the settings? The window edges, particularly for image journal entries, look cleaner to me without the border, though I know others may feel differently.

**Comment by Dorako** [comment]
You can disable the 'Theme app UI?' setting and refresh and it'll use the stock foundry theme for journal entries etc.
Considering you know the css variable name, if you want to just remove this border, I would recommend you use the Custom CSS module to create rules for the following three selectors:

.app.window-app
.app.window-app .window-content
.app.window-app .window-header

If the load order makes the Dorako UI styling take precedence, you can increase the specificity of the selectors, or use !important

**Comment by Dorako** [comment]
reverted this change in 1.5.4
