### ISSUE TITLE
Performance Issue When Dragging Windows

### ISSUE THREAD

**Issue by ByronThompson** [Dorako/pf2e-dorako-ui#76]
**Foundry Version:** 9 Build 269 (Forge Hosting)
**PF2E Version:** 3.13.5.16
**Module Version:** 1.5.4
**Other Modules Installed:** None
**Description:** Recent update causes windows (Such as character sheet, settings window, etc) to lag behind mouse when being moved. This issue is not present on previous versions.

https://user-images.githubusercontent.com/29874212/185554900-c63f3e7c-8b06-4192-b1ef-aa59fca49d23.mp4

**Comment by Dorako** [comment]
fix'd in 1.5.5
