### ISSUE TITLE
Target Lock Text Hard to Read

### ISSUE THREAD

**Issue by Armandeus66** [Dorako/pf2e-dorako-ui#77]
When using the module Target Lock, buttons in chat appear after rolling for damage and have the names of the targeted tokens above them. Originally the text is black, but when using this US, the text is very tiny and is white on a light background. It is difficult to read, and I would like to suggest a more contrasting color. Thanks.
https://github.com/WillNichols726/target-lock

**Comment by Dorako** [comment]
I'll have a look at this - I know there are several aspects of Target Lock that look kinda weird, because it doesn't use the standard class names

**Comment by Dorako** [comment]
Fixed by using the new https://github.com/MrVauxs/PF2e-Target-Damage instead
Using this fixes the text and buttons being weird:
<img width="304" alt="image" src="https://user-images.githubusercontent.com/1561190/194722813-58d71918-2f19-4541-a963-0db579ece917.png">
