### ISSUE TITLE
Option to disable portrait as GM when typing

### ISSUE THREAD

**Issue by ILikeCoolThings** [Dorako/pf2e-dorako-ui#78]
It would be nice to have the option to disable the portrait for the GM when they type in chat. Sometimes GMs type when selecting PCs, and the portrait appears as the PC, even when you have modules to mask you from doing so. 

For example, I have Cautious GM Pack module installed to not appear as a PC, but it still injects the PC's image.
![image](https://user-images.githubusercontent.com/54457140/188326622-1e38dc89-85eb-44b0-9a81-6ec7465764e5.png)

**Comment by Dorako** [comment]
Oh that's an interesting case, but it seems like a scenario that can only happen with that specific module, right? In a stock foundry scenario, the expected behaviour when a GM selects a PC token and says something, is for them to 'speak as' the token, right?

Cautious GM Pack is pretty popular, so I would not be averse to looking for the presence of the module and its settings, just trying to make sure I'm not missing something - My group never writes anything in chat, so there's lots of chat-related behaviour that I don't know a lot about.

**Comment by ILikeCoolThings** [comment]
Yeah - This would only happen with Cautious GM Pack. Without it, you would appear as normal. Stock just appears as if you are talking as the token, whatever you have selected. I turned it on after I was typing to my players after selecting a monster in a different room and they went wide eyed. :)

This is what it looks like as GM typing into chat with a token selected...
With UI mod and Cautious GM Pack both enabled:
![image](https://user-images.githubusercontent.com/54457140/188336101-96e9962c-18fa-462b-bab0-2ba3341e0e23.png)

With UI mod enabled and Cautious GM pack disabled:
![image](https://user-images.githubusercontent.com/54457140/188336080-c1044e33-902e-41aa-ae6b-9db930c1dbba.png)

With UI mod disabled and Cautious GM pack enabled:
![image](https://user-images.githubusercontent.com/54457140/188336157-dd2738e7-53b9-4394-b268-5a8ba382c50f.png)

With UI mod and Cautious GM Pack both disabled :
![image](https://user-images.githubusercontent.com/54457140/188336162-d5fcc82e-b031-4569-8391-984a7687a0c6.png)

**Comment by Dorako** [comment]
Yeah with this PR, speaking as a player character causes messages to have the name and avatar of the GM.
With the 'force out of character' setting of CGP turned on, you can select monsters or PC's and type, and the message will appear as if you had nothing selected.

If you're using 'disable speaking as PC', then you can still accidentally send a message from a monster.
Using the aforementioned Speaking As module https://github.com/MrVauxs/speaking-as makes this way less likely though, as it is very obvious that the message is going to be sent as the monster, and gives you affordances for overwriting the speaker without deselecting your token:
<img width="306" alt="CleanShot 2022-11-23 at 07 22 23@2x" src="https://user-images.githubusercontent.com/1561190/203483827-635ac075-e15c-4339-a0da-71378d64c793.png">

**Comment by ILikeCoolThings** [comment]
Thanks so much to the both of you
