### ISSUE TITLE
TokenActionHUD: -/+ Not showing for spell categories

### ISSUE THREAD

**Issue by Rikshy** [Dorako/pf2e-dorako-ui#89]
See picture below. They are properly shown without theming.
![grafik](https://user-images.githubusercontent.com/6615662/196150714-9baec077-be94-4329-abf3-c1cead7cc207.png)

**Comment by Symon-S** [comment]
Also noted that spells overlap with large lists, these are of course resolved by turning styling off and using the dorako ui styling in TAH

**Comment by Dorako** [comment]
In 1.8.0 the TAH theme is gone from Dorako UI, with a note about doing the above suggestion.
