### ISSUE TITLE
Cards tab is hidden

### ISSUE THREAD

**Issue by manuel-hegner** [Dorako/pf2e-dorako-ui#93]
The dorako UI (at least in dark mode) seems to hide the card tab.

**Comment by Dorako** [comment]
Which version are you using? This issue should have been fixed as of 1.7.0

**Comment by manuel-hegner** [comment]
You are so right. One should update to the newest version before making a bug report

**Comment by Dorako** [comment]
I'd rather have a bug report about something I've already fixed, than be missing a bug report about an issue I've never heard of!
