### ISSUE TITLE
Hide/modify damage taken messages

### ISSUE THREAD

**Issue by ditzer252** [Dorako/pf2e-dorako-ui#98]
Would it be within the scope of this wonderful module to have an option to disable the "Hide damage taken message" for the GM?  
Thanks for your consideration and thank you for this module.

**Comment by Dorako** [comment]
Yeah, I'm planning on having a setting for hiding or simplifying those messages.
I know some people track damage taken via modules, so the messages are just spam to them.

**Comment by ditzer252** [comment]
That's super news. Thank you.
________________________________

**Comment by Dorako** [comment]
This actually appears to be less straightforward than I had assumed.
The messages do not seem to contain any data that marks them as 'damage taken' messages, so I can't tell the difference between these or any other emote message, except by reading the text contents of the message, which is not great for localization.
Implementing this feature the proper way would probably require a pf2e-system PR first.

**Comment by Dorako** [comment]
I'm gonna close this issue because some change is needed on the system end before this is feasible at all.
Secondly, with official IWR support, it seems less smart to disable these message than earlier. Before, the GM always knew exactly how much damage a creature took, so it felt superfluous.

**Comment by ditzer252** [comment]
thanks, I agree that the messages are more useful now that we have IWR!
