### ISSUE TITLE
Compatibility with Narrator Tools Toolbar Button

### ISSUE THREAD

**Issue by apoapostolov** [Dorako/pf2e-dorako-ui#99]
Narrator Tools (https://github.com/elizeuangelo/fvtt-module-narrator-tools/) has a weird use of toolbar button. It applies switch logic to a button in the primary toolbar which is not done by any other mod, and therefore it isn't supported by Dorako UI. Thus, the button appears weird when turned off and turned on:

When turned off, the button appears without any border
![image](https://user-images.githubusercontent.com/4083812/198652888-30bdb1e0-30cc-48ed-9e61-02b7a8502d56.png)

When turned on, the button appears as a normal button that isn't turned on
![image](https://user-images.githubusercontent.com/4083812/198653051-c699b917-0a6c-4088-81d7-20dc42f41782.png)

The proper logic would be to apply the classes for switches to it, and ensure in turned off state it looks like a normal button.

**Comment by Dorako** [comment]
Didn't even see this issue, but fix'd in next release.
Do you know whether this used to work? I could have sworn I've fixed this before.

**Comment by apoapostolov** [comment]
Sorry, I don't remember seeing it fixed in the past.
